/**
 * Seed data for explore_places table.
 * This is used to initialize the database with recommended travel spots across Thailand.
 */
export const EXPLORE_PLACES_SEED = [
  // ── ภาคเหนือ (NORTH - 25 Places) ──
  {
    title: "ดอยอินทนนท์",
    locationName: "เชียงใหม่",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ภูเขา","หมอก","ธรรมชาติ"],
    regionId: "north",
    provinceId: "chiang-mai",
    description: "ยอดเขาที่สูงที่สุดในประเทศไทย โดดเด่นด้วยเส้นทางศึกษาธรรมชาติกิ่วแม่ปาน ปรากฏการณ์ทะเลหมอก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ดอยอินทนนท์"
  },
  {
    title: "วัดร่องขุ่น",
    locationName: "เชียงราย",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัด","ศิลปะ","สถาปัตยกรรม"],
    regionId: "north",
    provinceId: "chiang-rai",
    description: "สถาปัตยกรรมพุทธศิลป์ร่วมสมัยสีขาวบริสุทธิ์ ผลงานการออกแบบระดับโลก",
    sourceUrl: "https://goo.gl/maps/F6htP7BP1YAajeNc6"
  },
  {
    title: "กว๊านพะเยา",
    locationName: "พะเยา",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ทะเลสาบ","ชมวิว","พักผ่อน"],
    regionId: "north",
    provinceId: "phayao",
    description: "ทะเลสาบน้ำจืดขนาดใหญ่ที่สุดในภาคเหนือ มอบทัศนียภาพอันงดงามยามดวงอาทิตย์ตกดิน",
    sourceUrl: "https://maps.app.goo.gl/qFUb7zpE7aAAqQVc8"
  },
  {
    title: "เฮือนม่วนใจ๋",
    locationName: "เชียงใหม่",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารเหนือ","มิชลินไกด์","ร้านอาหาร"],
    regionId: "north",
    provinceId: "chiang-mai",
    description: "ร้านอาหารพื้นเมืองต้นตำรับล้านนา การันตีความอร่อยด้วยรางวัลระดับมิชลินไกด์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เฮือนม่วนใจ๋"
  },
  {
    title: "น้ำตกภูซาง",
    locationName: "พะเยา",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตกอุ่น","อุทยาน","แช่น้ำ"],
    regionId: "north",
    provinceId: "phayao",
    description: "น้ำตกกระแสน้ำอุ่นแห่งเดียวในประเทศไทยที่มีอุณหภูมิเฉลี่ย 35 องศาเซลเซียส",
    sourceUrl: "https://maps.app.goo.gl/y38Xx7XfWM2NeNwQ8"
  },
  {
    title: "Magic Mountain Cafe",
    locationName: "พะเยา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่","ทะเลหมอก","ภูเขา"],
    regionId: "north",
    provinceId: "phayao",
    description: "คาเฟ่เรือนไม้คลาสสิกบนจุดชมวิวผาช้างน้อย นำเสนอบรรยากาศทัศนียภาพทะเลหมอก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Magic+Mountain+Cafe"
  },
  {
    title: "วัดพระธาตุลำปางหลวง",
    locationName: "ลำปาง",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัด","ประวัติศาสตร์","ไหว้พระ"],
    regionId: "north",
    provinceId: "lampang",
    description: "วัดคู่บ้านคู่เมืองล้านนาที่งดงามด้วยสถาปัตยกรรมไม้เก่าแก่และเจดีย์อายุกว่าร้อยปี",
    sourceUrl: "https://goo.gl/maps/Ar3oqwnneu4BZGay5"
  },
  {
    title: "อุทยานแห่งชาติภูสอยดาว",
    locationName: "อุตรดิตถ์",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["เดินป่า","กางเต็นท์","ทุ่งดอกไม้"],
    regionId: "north",
    provinceId: "uttaradit",
    description: "จุดหมายปลายทางยอดนิยมของสายเดินป่า โดดเด่นด้วยลานสนกว้างใหญ่และทุ่งดอกหงอนนาค",
    sourceUrl: "https://goo.gl/maps/yAunvCs7dBxy8eZD8"
  },
  {
    title: "ข้าวซอยคุณยาย",
    locationName: "เชียงใหม่",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารเหนือ","ข้าวซอย","สตรีทฟู้ด"],
    regionId: "north",
    provinceId: "chiang-mai",
    description: "ร้านข้าวซอยระดับตำนานที่เรียบง่ายแต่นำเสนอน้ำแกงรสชาติเข้มข้นจัดจ้าน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ข้าวซอยคุณยาย"
  },
  {
    title: "The Library ChiangRai",
    locationName: "เชียงราย",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["บาร์ลับ","นั่งชิล","กลางคืน"],
    regionId: "north",
    provinceId: "chiang-rai",
    description: "บาร์สไตล์ลับที่ซ่อนตัวอยู่ในตัวเมืองเชียงราย มอบบรรยากาศเงียบสงบ อบอุ่น",
    sourceUrl: "https://maps.app.goo.gl/atKPYUHtMhbmzcwZ7"
  },
  {
    title: "อุทยานแห่งชาติดอยผากลอง",
    locationName: "แพร่",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["อุทยาน","หินประหลาด","ธรรมชาติ"],
    regionId: "north",
    provinceId: "phrae",
    description: "แหล่งรวมความน่าทึ่งทางธรณีวิทยา นำเสนอความมหัศจรรย์ของหินไดโนเสาร์และโขดหินแก่งหลวง",
    sourceUrl: "https://maps.app.goo.gl/2GNUwWpB3hySZjER8"
  },
  {
    title: "Fleur Cafe & Eatery",
    locationName: "เชียงใหม่",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่ในสวน","ถ่ายรูป","เบเกอรี่"],
    regionId: "north",
    provinceId: "chiang-mai",
    description: "คาเฟ่และร้านอาหารในสวนสไตล์อังกฤษที่เต็มไปด้วยมุมถ่ายรูปสุดโรแมนติก",
    sourceUrl: "https://maps.app.goo.gl/ghwo368f3duxrXgb9"
  },
  {
    title: "วัดพระธาตุเขาน้อย",
    locationName: "น่าน",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัด","จุดชมวิว","พระธาตุ"],
    regionId: "north",
    provinceId: "nan",
    description: "ปูชนียสถานเก่าแก่บนยอดเขา โดดเด่นด้วยองค์พระพุทธรูปปางลีลาและจุดชมวิวพาโนรามา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดพระธาตุเขาน้อย"
  },
  {
    title: "So Good Phayao",
    locationName: "พะเยา",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ร้านอาหารริมน้ำ","อาหารพื้นบ้าน","ชมวิว"],
    regionId: "north",
    provinceId: "phayao",
    description: "ร้านอาหารบรรยากาศเยี่ยมริมกว๊านพะเยา เสิร์ฟเมนูพื้นบ้านรสจัดจ้านพร้อมวิวดวงอาทิตย์ตก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=So+Good+Phayao"
  },
  {
    title: "Level Chiangrai",
    locationName: "เชียงราย",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["ผับ","ปาร์ตี้","ดนตรีสด"],
    regionId: "north",
    provinceId: "chiang-rai",
    description: "คลับบันเทิงยอดนิยมของสายปาร์ตี้ที่จัดเต็มด้วยดนตรีหลากหลายแนว",
    sourceUrl: "https://maps.app.goo.gl/cW48VUKz6g9A6igv8"
  },
  {
    title: "อ่างเก็บน้ำแม่ธิ",
    locationName: "ลำพูน",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["อ่างเก็บน้ำ","พักผ่อน","ธรรมชาติ"],
    regionId: "north",
    provinceId: "lamphun",
    description: "อ่างเก็บน้ำขนาดใหญ่ที่โอบล้อมด้วยขุนเขาเขียวขจี เหมาะสำหรับการมาสูดอากาศบริสุทธิ์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อ่างเก็บน้ำแม่ธิ"
  },
  {
    title: "สวนทูนอิน",
    locationName: "เชียงใหม่",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารเหนือ","มิชลินไกด์","ธรรมชาติ"],
    regionId: "north",
    provinceId: "chiang-mai",
    description: "ร้านอาหารระดับมิชลินไกด์ที่ซ่อนตัวอยู่ท่ามกลางป่าเขียวขจี นำเสนอความอร่อยของอาหารเหนือ",
    sourceUrl: "https://goo.gl/maps/ykxyapQ7c4d3Ugxt9"
  },
  {
    title: "วัดสันป่ายางหลวง",
    locationName: "ลำพูน",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดสวย","ศิลปะล้านนา","ไหว้พระ"],
    regionId: "north",
    provinceId: "lamphun",
    description: "วัดใจกลางเมืองที่มีความวิจิตรตระการตา โดดเด่นด้วยวิหารพระโขงเขียวและการแกะสลักลวดลาย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดสันป่ายางหลวง"
  },
  {
    title: "paper plane",
    locationName: "เชียงใหม่",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่มินิมอล","เบเกอรี่","ถ่ายรูป"],
    regionId: "north",
    provinceId: "chiang-mai",
    description: "คาเฟ่มินิมอลโทนสีขาวสะอาดตาที่ให้ความรู้สึกอบอุ่นเป็นกันเอง",
    sourceUrl: "https://maps.app.goo.gl/hrTiLFN7HJ5Ncu4cA"
  },
  {
    title: "น้ำตกก้อหลวง",
    locationName: "ลำพูน",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตก","ป่าเขา","ธรรมชาติ"],
    regionId: "north",
    provinceId: "lamphun",
    description: "น้ำตกหินปูนที่ตั้งอยู่ในอุทยานแห่งชาติแม่ปิง ไหลลดหลั่นผ่านหน้าผาลงสู่แอ่งน้ำสีฟ้าเขียวมรกต",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกก้อหลวง"
  },
  {
    title: "วัดจอมสวรรค์",
    locationName: "แพร่",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดพม่า","ไม้สัก","ประวัติศาสตร์"],
    regionId: "north",
    provinceId: "phrae",
    description: "โโบราณสถานอันทรงคุณค่าที่สร้างด้วยศิลปะพม่าและโครงสร้างไม้สักทั้งหลัง",
    sourceUrl: "https://maps.app.goo.gl/gFW1AJgseaZYbHYS7"
  },
  {
    title: "hind cafe",
    locationName: "พะเยา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["กาแฟสเปเชียลตี้","มินิมอล","เบเกอรี่"],
    regionId: "north",
    provinceId: "phayao",
    description: "คาเฟ่สไตล์มินิมอลที่เน้นความเรียบง่าย นำเสนอกาแฟคัดพิเศษ และเบเกอรี่ทำเอง",
    sourceUrl: "https://maps.app.goo.gl/4qSQULHpzTBNcm5RA"
  },
  {
    title: "อุทยานแห่งชาติลำน้ำน่าน",
    locationName: "อุตรดิตถ์",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["กางเต็นท์","ล่องแพ","ทะเลสาบ"],
    regionId: "north",
    provinceId: "uttaradit",
    description: "ผืนป่าอุดมสมบูรณ์ที่มาพร้อมลานกางเต็นท์ริมน้ำและกิจกรรมล่องแพชิลๆ",
    sourceUrl: "https://goo.gl/maps/2VgGF8tJupvhP3cq9"
  },
  {
    title: "แมกโนเลีย คาเฟ่",
    locationName: "เชียงใหม่",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารไทย","มิชลินไกด์","ร้านอาหาร"],
    regionId: "north",
    provinceId: "chiang-mai",
    description: "ร้านอาหารไทยต้นตำรับที่พิถีพิถันในการปรุงและจัดจานอย่างงดงาม",
    sourceUrl: "https://maps.app.goo.gl/ZURvvS3QLsUz9qLD8"
  },
  {
    title: "วัดพระธาตุดอยพระฌาน",
    locationName: "ลำปาง",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดสวย","จุดชมวิว","พระใหญ่"],
    regionId: "north",
    provinceId: "lampang",
    description: "วัดสวยอันซีนสไตล์ล้านนาดั้งเดิม ประดิษฐานพระใหญ่ไดบุตสึบนยอดเขาสูง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดพระธาตุดอยพระฌาน"
  },
  // ── ภาคอีสาน (NORTHEAST - 40 Places) ──
  {
    title: "อุทยานแห่งชาติภูเรือ",
    locationName: "เลย",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ภูเขา","ทะเลหมอก","ธรรมชาติ"],
    regionId: "northeast",
    provinceId: "loei",
    description: "ยอดภูที่หนาวเย็นตลอดปี มีจุดชมทะเลหมอกและทิวทัศน์ภูเขาสลับซับซ้อนที่สวยงามตระการตา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานแห่งชาติภูเรือ"
  },
  {
    title: "อุทยานแห่งชาติผาแต้ม",
    locationName: "อุบลราชธานี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ชมวิว","ประวัติศาสตร์","แม่น้ำโขง"],
    regionId: "northeast",
    provinceId: "ubon-ratchathani",
    description: "จุดชมแสงแรกของสยาม พร้อมภาพเขียนสีประวัติศาสตร์และวิวแม่น้ำโขงระดับตระการตา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานแห่งชาติผาแต้ม"
  },
  {
    title: "สามพันโบก",
    locationName: "อุบลราชธานี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["แก่งหิน","แม่น้ำโขง","ล่องเรือ"],
    regionId: "northeast",
    provinceId: "ubon-ratchathani",
    description: "ประติมากรรมทางธรรมชาติหรือแกรนด์แคนยอนเมืองไทยที่มีแอ่งหินกว่าสามพันแอ่งริมแม่น้ำโขง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สามพันโบก"
  },
  {
    title: "หินสามวาฬ",
    locationName: "บึงกาฬ",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["จุดชมวิว","หน้าผา","ป่าไม้"],
    regionId: "northeast",
    provinceId: "bueng-kan",
    description: "โขดหินอายุ 75 ล้านปีรูปทรงวาฬสามพ่อแม่ลูกยื่นออกไปหน้าผา เป็นจุดชมวิวที่อลังการและแปลกตา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หินสามวาฬ"
  },
  {
    title: "ทะเลบัวแดง",
    locationName: "อุดรธานี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ล่องเรือ","ทุ่งดอกไม้","ถ่ายรูป"],
    regionId: "northeast",
    provinceId: "udon-thani",
    description: "บึงน้ำกว้างใหญ่ที่เต็มไปด้วยดอกบัวสายสีชมพูบานสะพรั่งสุดลูกหูลูกตาในช่วงเช้าตรู่ของฤดูหนาว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ทะเลบัวแดง"
  },
  {
    title: "ภูลมโล",
    locationName: "เลย",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ซากุระเมืองไทย","ภูเขา","ดอกไม้"],
    regionId: "northeast",
    provinceId: "loei",
    description: "หุบเขาสีชมพูที่เต็มไปด้วยต้นนางพญาเสือโคร่งบานสะพรั่งตระการตาสร้างความประทับใจในช่วงต้นปี",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ภูลมโล"
  },
  {
    title: "อุทยานแห่งชาติเขาใหญ่",
    locationName: "นครราชสีมา",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["กางเต็นท์","น้ำตก","สัตว์ป่า"],
    regionId: "northeast",
    provinceId: "nakhon-ratchasima",
    description: "มรดกโลกทางธรรมชาติที่มีป่าอุดมสมบูรณ์ น้ำตกสวยงาม และเส้นทางศึกษาธรรมชาติที่สมบูรณ์แบบ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานแห่งชาติเขาใหญ่"
  },
  {
    title: "ภูผาม่าน",
    locationName: "ขอนแก่น",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ภูเขาหินปูน","ถ้ำ","ธรรมชาติ"],
    regionId: "northeast",
    provinceId: "khon-kaen",
    description: "ภูเขาหินปูนสูงตระหง่านที่มีถ้ำและสภาพแวดล้อมทางธรรมชาติอันเงียบสงบเหมาะแก่การแคมป์ปิ้ง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ภูผาม่าน"
  },
  {
    title: "ถ้ำนาคา",
    locationName: "บึงกาฬ",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ความเชื่อ","ถ้ำ","เดินป่า"],
    regionId: "northeast",
    provinceId: "bueng-kan",
    description: "ถ้ำลึกลับที่มีหินรูปร่างคล้ายเกล็ดพญานาคยักษ์ เป็นสถานที่ศักดิ์สิทธิ์และเส้นทางเดินป่าที่ท้าทาย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถ้ำนาคา"
  },
  {
    title: "ทุ่งดอกกระเจียว",
    locationName: "ชัยภูมิ",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ทุ่งดอกไม้","หน้าฝน","ธรรมชาติ"],
    regionId: "northeast",
    provinceId: "chaiyaphum",
    description: "ทุ่งดอกไม้สีชมพูอมม่วงที่เบ่งบานต้อนรับความชุ่มฉ่ำท่ามกลางสายหมอกในฤดูฝนของทุกปี",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ทุ่งดอกกระเจียว"
  },
  {
    title: "น้ำตกเจ็ดสี",
    locationName: "บึงกาฬ",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตก","หน้าฝน","ธรรมชาติ"],
    regionId: "northeast",
    provinceId: "bueng-kan",
    description: "น้ำตกที่สวยงามตระการตาซ่อนตัวอยู่ในผืนป่าอันอุดมสมบูรณ์ เหมาะสำหรับการท่องเที่ยวในฤดูฝน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกเจ็ดสี"
  },
  {
    title: "อุทยานแห่งชาติภูจองนายอย",
    locationName: "อุบลราชธานี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ลานหิน","น้ำตก","ป่าไม้"],
    regionId: "northeast",
    provinceId: "ubon-ratchathani",
    description: "ผืนป่าอันสมบูรณ์ที่มีทุ่งดอกไม้บนลานหินและน้ำตกขนาดใหญ่ที่สวยงามตระการตาในช่วงปลายฝนต้นหนาว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานแห่งชาติภูจองนายอย"
  },
  {
    title: "ถนนคนเดินเชียงคาน",
    locationName: "เลย",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["บ้านไม้โบราณ","ริมโขง","สโลว์ไลฟ์"],
    regionId: "northeast",
    provinceId: "loei",
    description: "เมืองสโลว์ไลฟ์ริมแม่น้ำโขงที่มีบ้านไม้เก่าแก่และวัฒนธรรมท้องถิ่นอันเป็นเอกลักษณ์ดั้งเดิม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถนนคนเดินเชียงคาน"
  },
  {
    title: "อุทยานประวัติศาสตร์พนมรุ้ง",
    locationName: "บุรีรัมย์",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ปราสาทหิน","ประวัติศาสตร์","ขอมโบราณ"],
    regionId: "northeast",
    provinceId: "buriram",
    description: "ปราสาทหินทรายสีชมพูบนยอดภูเขาไฟที่ดับแล้ว สถาปัตยกรรมขอมที่ยิ่งใหญ่และน่าเกรงขาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานประวัติศาสตร์พนมรุ้ง"
  },
  {
    title: "วัดป่าถ้ำบูชา",
    locationName: "บึงกาฬ",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดป่า","ปฏิบัติธรรม","เงียบสงบ"],
    regionId: "northeast",
    provinceId: "bueng-kan",
    description: "สถานที่ปฏิบัติธรรมอันเงียบสงบและร่มรื่น ท่ามกลางสภาพแวดล้อมทางธรรมชาติของป่าเขา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดป่าถ้ำบูชา"
  },
  {
    title: "วัดผาตากเสื้อ",
    locationName: "หนองคาย",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["สกายวอล์ค","จุดชมวิว","ริมโขง"],
    regionId: "northeast",
    provinceId: "nong-khai",
    description: "วัดที่มีสกายวอล์คกระจกใสยื่นออกไปหน้าผา เพื่อชมวิวแม่น้ำโขงและฝั่งประเทศลาวแบบพาโนรามา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดผาตากเสื้อ"
  },
  {
    title: "วัดป่าภูก้อน",
    locationName: "อุดรธานี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดสวย","พระนอน","ภูเขา"],
    regionId: "northeast",
    provinceId: "udon-thani",
    description: "พระวิหารงดงามบนยอดเขาสูง ภายในประดิษฐานพระพุทธไสยาสน์ที่ทำจากหินอ่อนสีขาวอันวิจิตร",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดป่าภูก้อน"
  },
  {
    title: "วัดสิรินธรวรารามภูพร้าว",
    locationName: "อุบลราชธานี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดเรืองแสง","ถ่ายรูป","ชมวิว"],
    regionId: "northeast",
    provinceId: "ubon-ratchathani",
    description: "วัดเรืองแสงที่มีตัวอุโบสถลวดลายต้นกัลปพฤกษ์ส่องประกายสว่างไสวอย่างน่าอัศจรรย์ในยามค่ำคืน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดสิรินธรวรารามภูพร้าว"
  },
  {
    title: "อุทยานประวัติศาสตร์พิมาย",
    locationName: "นครราชสีมา",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ปราสาทหิน","โบราณสถาน","ขอมโบราณ"],
    regionId: "northeast",
    provinceId: "nakhon-ratchasima",
    description: "ปราสาทหินสถาปัตยกรรมขอมที่ใหญ่ที่สุดในประเทศไทย เต็มไปด้วยเรื่องราวทางประวัติศาสตร์โบราณ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานประวัติศาสตร์พิมาย"
  },
  {
    title: "พุทธอุทยานพระมงคลมิ่งเมือง",
    locationName: "อำนาจเจริญ",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["พระองค์ใหญ่","ทำบุญ","ร่มรื่น"],
    regionId: "northeast",
    provinceId: "amnat-charoen",
    description: "แลนด์มาร์คศักดิ์สิทธิ์ประจำเมืองที่มีพระพุทธรูปปางมารวิชัยองค์ใหญ่กลางป่าที่ร่มรื่นและเงียบสงบ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พุทธอุทยานพระมงคลมิ่งเมือง"
  },
  {
    title: "พิพิธภัณฑ์สิรินธร",
    locationName: "กาฬสินธุ์",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ไดโนเสาร์","พิพิธภัณฑ์","แหล่งเรียนรู้"],
    regionId: "northeast",
    provinceId: "kalasin",
    description: "ศูนย์วิจัยและจัดแสดงซากฟอสซิลไดโนเสาร์ที่มีความสมบูรณ์และใหญ่ที่สุดในเอเชียตะวันออกเฉียงใต้",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พิพิธภัณฑ์สิรินธร"
  },
  {
    title: "พระธาตุพนม",
    locationName: "นครพนม",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["พระธาตุ","สิ่งศักดิ์สิทธิ์","ริมโขง"],
    regionId: "northeast",
    provinceId: "nakhon-phanom",
    description: "ปูชนียสถานศักดิ์สิทธิ์คู่บ้านคู่เมืองริมแม่น้ำโขง ศูนย์รวมจิตใจและแรงศรัทธาของชาวอีสาน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พระธาตุพนม"
  },
  {
    title: "พระบรมธาตุนาดูน",
    locationName: "มหาสารคาม",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["โบราณสถาน","พระธาตุ","สิ่งศักดิ์สิทธิ์"],
    regionId: "northeast",
    provinceId: "maha-sarakham",
    description: "พุทธมณฑลแห่งอีสาน โบราณสถานสำคัญที่เก็บรักษาสิ่งศักดิ์สิทธิ์และร่องรอยอารยธรรมจำปาศรี",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พระบรมธาตุนาดูน"
  },
  {
    title: "วัดถ้ำแสงเพชร",
    locationName: "อำนาจเจริญ",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดป่า","ถ้ำ","ปฏิบัติธรรม"],
    regionId: "northeast",
    provinceId: "amnat-charoen",
    description: "วัดป่าที่มีถ้ำหินประกายระยิบระยับคล้ายเพชรเมื่อต้องแสงแดด เหมาะสำหรับการปฏิบัติธรรมอย่างยิ่ง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดถ้ำแสงเพชร"
  },
  {
    title: "หาดคำสมบูรณ์",
    locationName: "บึงกาฬ",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ทะเลน้ำจืด","เล่นน้ำ","พักผ่อน"],
    regionId: "northeast",
    provinceId: "bueng-kan",
    description: "ทะเลน้ำจืดริมบึงโขงหลงที่ได้รับฉายาว่าบางแสนอีสาน สามารถเล่นน้ำและพักผ่อนหย่อนใจได้อย่างดี",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดคำสมบูรณ์"
  },
  {
    title: "หาดสวนหิน",
    locationName: "สกลนคร",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดทราย","ทะเลเทียม","จุดถ่ายรูป"],
    regionId: "northeast",
    provinceId: "sakon-nakhon",
    description: "ทะเลเทียมอันซีนของภาคอีสานที่มีหาดทราย น้ำใส และโขดหินสวยงามให้บรรยากาศเหมือนอยู่ทะเลจริง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดสวนหิน"
  },
  {
    title: "บางแสน 2 เขื่อนอุบลรัตน์",
    locationName: "ขอนแก่น",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ริมเขื่อน","บางแสนอีสาน","ร้านอาหาร"],
    regionId: "northeast",
    provinceId: "khon-kaen",
    description: "ชายหาดริมเขื่อนอุบลรัตน์ที่ชาวอีสานนิยมมาเล่นน้ำและรับประทานอาหารริมหาดในวันหยุดพักผ่อน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=บางแสน+2+เขื่อนอุบลรัตน์"
  },
  {
    title: "บึงเกลือ",
    locationName: "ร้อยเอ็ด",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดทราย","กิจกรรมทางน้ำ","พักผ่อน"],
    regionId: "northeast",
    provinceId: "roi-et",
    description: "แหล่งน้ำขนาดใหญ่ที่มีหาดทรายขาวกว้างขวาง พร้อมกิจกรรมทางน้ำและเครื่องเล่นบานาน่าโบ๊ทมากมาย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=บึงเกลือ"
  },
  {
    title: "พัทยาน้อย เขื่อนสิรินธร",
    locationName: "อุบลราชธานี",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["พัทยาน้อย","แพอาหาร","เล่นน้ำ"],
    regionId: "northeast",
    provinceId: "ubon-ratchathani",
    description: "แพร้านอาหารริมหาดทรายเขื่อนสิรินธร ให้ความรู้สึกผ่อนคลายเสมือนไปเที่ยวหาดพัทยาของจริง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พัทยาน้อย+เขื่อนสิรินธร"
  },
  {
    title: "หาดสลึง",
    locationName: "อุบลราชธานี",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดทรายริมโขง","ล่องเรือ","ธรรมชาติ"],
    regionId: "northeast",
    provinceId: "ubon-ratchathani",
    description: "หาดทรายริมฝั่งแม่น้ำโขงที่สวยงามในฤดูแล้ง และเป็นจุดตั้งต้นในการล่องเรือชมวิวธรรมชาติที่ยิ่งใหญ่",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดสลึง"
  },
  {
    title: "หาดสีกาย",
    locationName: "หนองคาย",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดลับ","ริมโขง","เงียบสงบ"],
    regionId: "northeast",
    provinceId: "nong-khai",
    description: "หาดทรายลับริมแม่น้ำโขงที่น้ำเย็นสบาย บรรยากาศเงียบสงบเหมาะแก่การนั่งชิลและหลบร้อนในฤดูร้อน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดสีกาย"
  },
  {
    title: "ทะเลสาบทุ่งกุลาร้องไห้",
    locationName: "สุรินทร์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ทะเลสาบ","ปั่นเรือถีบ","ชมพระอาทิตย์ตก"],
    regionId: "northeast",
    provinceId: "surin",
    description: "ทะเลสาบน้ำจืดกว้างใหญ่ที่ปรับปรุงพื้นที่ให้กลายเป็นสถานที่เล่นน้ำและจุดชมวิวพระอาทิตย์ตกที่สวยงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ทะเลสาบทุ่งกุลาร้องไห้"
  },
  {
    title: "มองโขง cafe' and camping",
    locationName: "อุบลราชธานี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ฟีลทะเล","แคมป์ปิ้ง","ริมโขง"],
    regionId: "northeast",
    provinceId: "ubon-ratchathani",
    description: "คาเฟ่ฟีลทะเลริมแม่น้ำโขงสองสี มีลมพัดเย็นสบาย ให้บริการทั้งเครื่องดื่ม อาหาร และลานแคมป์ปิ้ง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=มองโขง+cafe'+and+camping"
  },
  {
    title: "KIN Matcha",
    locationName: "ขอนแก่น",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ชาเขียวมัทฉะ","สไตล์ญี่ปุ่น","โฮมคาเฟ่"],
    regionId: "northeast",
    provinceId: "khon-kaen",
    description: "คาเฟ่มัทฉะพรีเมียมวัตถุดิบส่งตรงจากญี่ปุ่น ตกแต่งร้านสไตล์มินิมอลให้ความรู้สึกอบอุ่นผ่อนคลายอย่างมาก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=KIN+Matcha"
  },
  {
    title: "AURA Cafe and Restaurant",
    locationName: "ขอนแก่น",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["สไตล์ยุโรป","สวนสวย","มุมถ่ายรูป"],
    regionId: "northeast",
    provinceId: "khon-kaen",
    description: "คาเฟ่บรรยากาศสวนป่าสไตล์ยุโรป ราวกับหลุดเข้าไปในเทพนิยาย มีมุมจัดตกแต่งสำหรับถ่ายรูปสวยงามเพียบ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=AURA+Cafe+and+Restaurant"
  },
  {
    title: "Option Coffee Bar",
    locationName: "อุดรธานี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["โมเดิร์น","สเปเชียลตี้คอฟฟี่","ถ่ายรูป"],
    regionId: "northeast",
    provinceId: "udon-thani",
    description: "คาเฟ่สไตล์โมเดิร์นคุมโทนสีขาวและเงิน โดดเด่นด้วยเมล็ดกาแฟสเปเชียลตี้และมีตู้ถ่ายรูปเก๋ไก๋บริการ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Option+Coffee+Bar"
  },
  {
    title: "บ้านเฮง",
    locationName: "ขอนแก่น",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารเช้า","มิชลินไกด์","ไข่กระทะ"],
    regionId: "northeast",
    provinceId: "khon-kaen",
    description: "ร้านอาหารเช้าชื่อดังที่การันตีความอร่อยด้วยมิชลินไกด์ เสิร์ฟไข่กระทะและขนมปังปิ้งรสเลิศคู่กับกาแฟ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=บ้านเฮง"
  },
  {
    title: "เป้ง ก๋วยเตี๋ยวเป็ด",
    locationName: "อุดรธานี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["สตรีทฟู้ด","มิชลินไกด์","ก๋วยเตี๋ยวเป็ด"],
    regionId: "northeast",
    provinceId: "udon-thani",
    description: "ร้านสตรีทฟู้ดก๋วยเตี๋ยวเป็ดตุ๋นต้นตำรับรสชาติเข้มข้น การันตีคุณภาพความอร่อยด้วยรางวัลมิชลินไกด์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เป้ง+ก๋วยเตี๋ยวเป็ด"
  },
  {
    title: "ตลาดเซฟวัน",
    locationName: "นครราชสีมา",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["ตลาดกลางคืน","สตรีทฟู้ด","ช้อปปิ้ง"],
    regionId: "northeast",
    provinceId: "nakhon-ratchasima",
    description: "ตลาดกลางคืนที่กว้างใหญ่ที่สุดในภาคอีสาน แหล่งรวมสตรีทฟู้ดชั้นยอด เสื้อผ้า และสินค้าแฟชั่นมากมาย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดเซฟวัน"
  },
  {
    title: "ถนนคนเดินขอนแก่น",
    locationName: "ขอนแก่น",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["ถนนคนเดิน","ของกินพื้นเมือง","เดินเล่น"],
    regionId: "northeast",
    provinceId: "khon-kaen",
    description: "แหล่งช้อปปิ้งและศูนย์รวมของกินพื้นเมืองยามค่ำคืนวันเสาร์ที่คึกคักและมีชีวิตชีวาที่สุดในตัวเมือง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถนนคนเดินขอนแก่น"
  },
  // ── ภาคกลาง (CENTRAL - 38 Places) ──
  {
    title: "พระบรมมหาราชวัง",
    locationName: "กรุงเทพมหานคร",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["พระราชวัง","ประวัติศาสตร์","แลนด์มาร์ค"],
    regionId: "central",
    provinceId: "bangkok",
    description: "อดีตศูนย์กลางการปกครองและที่ประทับของพระมหากษัตริย์ โดดเด่นด้วยสถาปัตยกรรมไทยวิจิตรตระการตา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พระบรมมหาราชวัง"
  },
  {
    title: "ถนนข้าวสาร",
    locationName: "กรุงเทพมหานคร",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["เที่ยวกลางคืน","บาร์","สตรีทฟู้ด"],
    regionId: "central",
    provinceId: "bangkok",
    description: "แหล่งแฮงก์เอาต์ยามค่ำคืนระดับโลก ศูนย์รวมนักเดินทาง บาร์ และสตรีทฟู้ดที่คึกคักตลอดคืน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถนนข้าวสาร"
  },
  {
    title: "ตลาดนัดจตุจักร",
    locationName: "กรุงเทพมหานคร",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ช้อปปิ้ง","สตรีทฟู้ด","วันหยุด"],
    regionId: "central",
    provinceId: "bangkok",
    description: "ตลาดนัดสุดสัปดาห์ที่ใหญ่ที่สุดในโลก แหล่งรวมอาหารหลากหลายและสินค้าทุกประเภท",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดนัดจตุจักร"
  },
  {
    title: "JODD FAIRS พระราม 9",
    locationName: "กรุงเทพมหานคร",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["ตลาดกลางคืน","แฮงก์เอาต์","วัยรุ่น"],
    regionId: "central",
    provinceId: "bangkok",
    description: "ตลาดกลางคืนใจกลางเมืองที่โดดเด่นด้วยอาหารสตรีทฟู้ดชื่อดังและบรรยากาศการเดินเล่นสุดชิล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=JODD+FAIRS+พระราม+9"
  },
  {
    title: "สวนสยาม",
    locationName: "กรุงเทพมหานคร",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["สวนสนุก","สวนน้ำ","ครอบครัว"],
    regionId: "central",
    provinceId: "bangkok",
    description: "สวนสนุกและสวนน้ำระดับตำนานของไทย มีเครื่องเล่นหลากหลายเหมาะสำหรับการพักผ่อนแบบครอบครัว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สวนสยาม"
  },
  {
    title: "Chocolate Ville",
    locationName: "กรุงเทพมหานคร",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["ถ่ายรูป","ดินเนอร์","ธีมปาร์ค"],
    regionId: "central",
    provinceId: "bangkok",
    description: "สถานที่พักผ่อนและร้านอาหารสไตล์หมู่บ้านยุโรป มีมุมถ่ายรูปและแสงสียามค่ำคืนที่สวยงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Chocolate+Ville"
  },
  {
    title: "เกาะเกร็ด",
    locationName: "นนทบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วิถีชุมชน","ริมน้ำ","วัฒนธรรมมอญ"],
    regionId: "central",
    provinceId: "nonthaburi",
    description: "ชุมชนคนมอญบนเกาะกลางน้ำเจ้าพระยา มีชื่อเสียงเรื่องเครื่องปั้นดินเผาและขนมไทยโบราณ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เกาะเกร็ด"
  },
  {
    title: "อาลมดี Cafe",
    locationName: "นนทบุรี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ริมน้ำ","พักผ่อน","ถ่ายรูป"],
    regionId: "central",
    provinceId: "nonthaburi",
    description: "คาเฟ่ริมแม่น้ำเจ้าพระยา บรรยากาศร่มรื่น นำเสนอเมนูเครื่องดื่มและอาหารในสไตล์ชิคๆ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อาลมดี+Cafe"
  },
  {
    title: "บ้าน ๑,๐๐๐ ไม้ cafe & farm",
    thumbnailUrl: "https://images.unsplash.com/photo-1501183638710-841dd1904471?q=80&w=600",
    locationName: "ปทุมธานี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ธรรมชาติ","ครอบครัว","ฟาร์ม"],
    regionId: "central",
    provinceId: "pathumthani",
    description: "คาเฟ่เชิงเกษตรที่ร่มรื่นด้วยแมกไม้ ให้เด็กๆ และครอบครัวได้สัมผัสธรรมชาติอย่างใกล้ชิด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=บ้าน+๑,๐๐๐+ไม้+cafe+&+farm"
  },
  {
    title: "ตลาดแบล็คมาร์เก็ต",
    locationName: "สมุทรปราการ",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["ตลาดกลางคืน","ติดรถไฟฟ้า","ชิลเอาท์"],
    regionId: "central",
    provinceId: "samut-prakan",
    description: "ตลาดนัดกลางคืนยอดฮิตติดรถไฟฟ้า แหล่งรวมของกินฟีลกู้ดและจุดแฮงก์เอาต์ยามเย็น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดแบล็คมาร์เก็ต"
  },
  {
    title: "ตลาดมหาชัย",
    locationName: "สมุทรสาคร",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารทะเล","ตลาดสด","ของฝาก"],
    regionId: "central",
    provinceId: "samut-sakhon",
    description: "แหล่งรวมอาหารทะเลสดและแปรรูปที่ใหญ่และมีชื่อเสียงที่สุดแห่งหนึ่งของประเทศไทย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดมหาชัย"
  },
  {
    title: "วัดนักบุญอันนา",
    locationName: "สมุทรสาคร",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["โบสถ์คริสต์","สถาปัตยกรรม","ริมน้ำ"],
    regionId: "central",
    provinceId: "samut-sakhon",
    description: "โบสถ์คริสต์ที่มีรูปปั้นนักบุญอันนาขนาดใหญ่ที่สุดในเอเชีย หมุนได้ 360 องศา หันหน้าออกสู่แม่น้ำ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดนักบุญอันนา"
  },
  {
    title: "ตลาดน้ำอัมพวา",
    locationName: "สมุทรสงคราม",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ตลาดน้ำ","วิถีชีวิต","ริมคลอง"],
    regionId: "central",
    provinceId: "samut-songkhram",
    description: "ตลาดน้ำยามเย็นสุดคลาสสิก อิ่มอร่อยกับอาหารริมคลองและกิจกรรมล่องเรือชมหิ่งห้อย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดน้ำอัมพวา"
  },
  {
    title: "ตลาดน้ำทุ่งบัวแดง",
    locationName: "นครปฐม",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ทุ่งดอกไม้","ล่องเรือ","ถ่ายรูป"],
    regionId: "central",
    provinceId: "nakhon-pathom",
    description: "ตลาดน้ำเชิงเกษตรที่ให้นักท่องเที่ยวล่องเรือชมทุ่งดอกบัวแดงบานสะพรั่ง พร้อมเมนูจากสายบัว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดน้ำทุ่งบัวแดง"
  },
  {
    title: "Whispering Cafe",
    locationName: "นครปฐม",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["วินเทจ","มินิมอล","ธรรมชาติ"],
    regionId: "central",
    provinceId: "nakhon-pathom",
    description: "คาเฟ่สไตล์วินเทจในสวนร่มรื่น มอบความอบอุ่นและเงียบสงบ เหมาะกับการหลีกหนีความวุ่นวาย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Whispering+Cafe"
  },
  {
    title: "O2 Kaffee & Bistro",
    locationName: "นครปฐม",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["สวนมะพร้าว","ริมน้ำ","ร่มรื่น"],
    regionId: "central",
    provinceId: "nakhon-pathom",
    description: "คาเฟ่สุดชิลท่ามกลางร่องน้ำในสวนมะพร้าว ให้บรรยากาศการพักผ่อนอย่างแท้จริงใกล้กรุงเทพ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=O2+Kaffee+&+Bistro"
  },
  {
    title: "วัดใหญ่ชัยมงคล",
    locationName: "พระนครศรีอยุธยา",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดเก่าแก่","ประวัติศาสตร์","ไหว้พระ"],
    regionId: "central",
    provinceId: "phra-nakhon-sri-ayutthaya",
    description: "วัดสำคัญทางประวัติศาสตร์ โดดเด่นด้วยเจดีย์ชัยมงคลอันยิ่งใหญ่และพระพุทธไสยาสน์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดใหญ่ชัยมงคล"
  },
  {
    title: "ต้นมะม่วงคาเฟ่",
    locationName: "พระนครศรีอยุธยา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ริมน้ำ","พักผ่อน","ถ่ายรูป"],
    regionId: "central",
    provinceId: "phra-nakhon-sri-ayutthaya",
    description: "ร้านกาแฟริมแม่น้ำเจ้าพระยา ตกแต่งด้วยต้นไม้สุดร่มรื่น มีมุมให้ถ่ายรูปเช็คอินสวยงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ต้นมะม่วงคาเฟ่"
  },
  {
    title: "สวนบิ๊กเต้",
    locationName: "สระบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["สวนดอกไม้","ทิวทัศน์","ถ่ายรูป"],
    regionId: "central",
    provinceId: "saraburi",
    description: "แหล่งปลูกดอกเบญจมาศที่ใหญ่ที่สุดแห่งหนึ่ง มีดอกไม้หลากสีสันนับล้านดอกเบ่งบานต้อนรับนักท่องเที่ยว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สวนบิ๊กเต้"
  },
  {
    title: "อ่างเก็บน้ำมวกเหล็ก",
    locationName: "สระบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["อ่างเก็บน้ำ","วิวภูเขา","พระอาทิตย์ตก"],
    regionId: "central",
    provinceId: "saraburi",
    description: "จุดชมวิวพาโนรามาเหนืออ่างเก็บน้ำที่โอบล้อมด้วยภูเขา บรรยากาศร่มรื่นเหมาะแก่การพักผ่อน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อ่างเก็บน้ำมวกเหล็ก"
  },
  {
    title: "วัดพระนอนจักรสีห์วรวิหาร",
    locationName: "สิงห์บุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ไหว้พระ","สิ่งศักดิ์สิทธิ์","ศิลปะ"],
    regionId: "central",
    provinceId: "sing-buri",
    description: "พระอารามหลวงชั้นตรี เป็นที่ประดิษฐานพระพุทธไสยาสน์ขนาดใหญ่ที่มีพุทธลักษณะงดงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดพระนอนจักรสีห์วรวิหาร"
  },
  {
    title: "ตลาดไทยย้อนยุคบ้านระจัน",
    locationName: "สิงห์บุรี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ย้อนยุค","วิถีชุมชน","อาหารพื้นบ้าน"],
    regionId: "central",
    provinceId: "sing-buri",
    description: "ตลาดย้อนยุคที่พ่อค้าแม่ค้าแต่งกายชุดไทยโบราณ เต็มไปด้วยอาหารพื้นบ้านและการแสดงอิงประวัติศาสตร์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดไทยย้อนยุคบ้านระจัน"
  },
  {
    title: "วัดม่วง",
    locationName: "อ่างทอง",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["พระองค์ใหญ่","ขอพร","แลนด์มาร์ค"],
    regionId: "central",
    provinceId: "ang-thong",
    description: "ศาสนสถานที่มีพระพุทธรูปองค์ใหญ่ที่สุดในโลก เป็นแลนด์มาร์คสำคัญที่ผู้คนนิยมมาขอพรที่ปลายพระหัตถ์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดม่วง"
  },
  {
    title: "สวนนกชัยนาท",
    locationName: "ชัยนาท",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["สวนนก","ครอบครัว","เรียนรู้"],
    regionId: "central",
    provinceId: "chai-nat",
    description: "แหล่งเรียนรู้ธรรมชาติที่มีกรงนกขนาดใหญ่ที่สุดในเอเชีย พร้อมจัดแสดงพันธุ์ปลาลุ่มแม่น้ำเจ้าพระยา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สวนนกชัยนาท"
  },
  {
    title: "อุทยานมังกรสวรรค์",
    locationName: "สุพรรณบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["พิพิธภัณฑ์","ศิลปะจีน","แลนด์มาร์ค"],
    regionId: "central",
    provinceId: "suphan-buri",
    description: "พิพิธภัณฑ์รูปร่างมังกรขนาดมหึมา จัดแสดงประวัติศาสตร์อารยธรรมจีนที่น่าตื่นตาตื่นใจ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานมังกรสวรรค์"
  },
  {
    title: "ตลาดสามชุก",
    locationName: "สุพรรณบุรี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ตลาดโบราณ","วิถีชีวิต","ของฝาก"],
    regionId: "central",
    provinceId: "suphan-buri",
    description: "ตลาดห้องแถวไม้เก่าแก่อายุกว่า 100 ปี เสน่ห์แห่งวิถีชีวิตดั้งเดิมที่เต็มไปด้วยของอร่อยหาทานยาก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดสามชุก"
  },
  {
    title: "อุทยานแห่งชาติเอราวัณ",
    locationName: "กาญจนบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตก","เดินป่า","ร่มรื่น"],
    regionId: "central",
    provinceId: "kanchanaburi",
    description: "น้ำตกชื่อดังที่มีความสวยงามถึง 7 ชั้น น้ำใสสีฟ้าอมเขียวมรกตท่ามกลางป่าที่อุดมสมบูรณ์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานแห่งชาติเอราวัณ"
  },
  {
    title: "ทางรถไฟสายมรณะ",
    locationName: "กาญจนบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ประวัติศาสตร์","ชมวิว","จุดถ่ายรูป"],
    regionId: "central",
    provinceId: "kanchanaburi",
    description: "เส้นทางรถไฟสายประวัติศาสตร์สมัยสงครามโลกครั้งที่ 2 เลียบหน้าผาสูงชันเหนือแม่น้ำแควน้อย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ทางรถไฟสายมรณะ"
  },
  {
    title: "ตลาดน้ำดำเนินสะดวก",
    locationName: "ราชบุรี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ตลาดน้ำ","คึกคัก","ยอดนิยม"],
    regionId: "central",
    provinceId: "ratchaburi",
    description: "ตลาดน้ำแห่งแรกและมีชื่อเสียงที่สุดของไทย คลาคล่ำด้วยเรือพายขายผลไม้และอาหารนานาชนิด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดน้ำดำเนินสะดวก"
  },
  {
    title: "ถ้ำเขาบิน",
    locationName: "ราชบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ถ้ำ","หินงอกหินย้อย","ผจญภัย"],
    regionId: "central",
    provinceId: "ratchaburi",
    description: "ถ้ำที่สวยงามประดับประดาด้วยหินงอกหินย้อยตระการตา แบ่งเป็นห้องต่างๆ ที่ประดับไฟอย่างงดงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถ้ำเขาบิน"
  },
  {
    title: "วนอุทยานเขานางพันธุรัต",
    locationName: "เพชรบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ภูเขา","เดินป่า","จุดชมวิว"],
    regionId: "central",
    provinceId: "phetchaburi",
    description: "ภูเขาหินปูนรูปทรงแปลกตา มีเส้นทางศึกษาธรรมชาติและจุดชมวิวที่เชื่อมโยงกับวรรณคดีไทย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วนอุทยานเขานางพันธุรัต"
  },
  {
    title: "หาดหัวหิน",
    locationName: "ประจวบคีรีขันธ์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ชายหาด","ขี่ม้า","พักผ่อน"],
    regionId: "central",
    provinceId: "prachuap-khiri-khan",
    description: "ชายหาดตากอากาศคลาสสิก มีเอกลักษณ์ด้วยการขี่ม้าเลียบชายหาด ทรายขาวสะอาดและคลื่นสงบ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดหัวหิน"
  },
  {
    title: "หาดทับสะแก",
    locationName: "ประจวบคีรีขันธ์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["เงียบสงบ","เดินชายหาด","ธรรมชาติ"],
    regionId: "central",
    provinceId: "prachuap-khiri-khan",
    description: "ทะเลที่เงียบสงบ น้ำทะเลไล่สีสวยงาม เหมาะสำหรับผู้ที่ต้องการเดินเล่นซึมซับธรรมชาติแบบส่วนตัว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดทับสะแก"
  },
  {
    title: "หาดบ้านกรูด",
    locationName: "ประจวบคีรีขันธ์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ชายหาด","พักผ่อน","ขับรถเที่ยว"],
    regionId: "central",
    provinceId: "prachuap-khiri-khan",
    description: "ชายหาดทอดยาวสีขาวอมครีม บรรยากาศบริสุทธิ์ มีที่พักและร้านอาหารให้บริการริมถนนเลียบหาด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดบ้านกรูด"
  },
  {
    title: "อ่าวบ่อทองหลาง",
    locationName: "ประจวบคีรีขันธ์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["อ่าว","น้ำใส","ทะเลแหวก"],
    regionId: "central",
    provinceId: "prachuap-khiri-khan",
    description: "เวิ้งอ่าวขนาดเล็กรูปร่างครึ่งวงกลม น้ำทะเลสีฟ้าใส มีทะเลแหวกให้เดินไปเกาะเล็กๆ ยามน้ำลด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อ่าวบ่อทองหลาง"
  },
  {
    title: "หาดทรายน้อย",
    locationName: "ประจวบคีรีขันธ์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดลับ","น้ำใส","เล่นน้ำ"],
    regionId: "central",
    provinceId: "prachuap-khiri-khan",
    description: "ชายหาดเล็กๆ ขนาบด้วยหน้าผาสูงชัน น้ำทะเลสีเขียวใส ทรายขาวละเอียดคล้ายทะเลฝั่งอันดามัน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดทรายน้อย"
  },
  {
    title: "ตลาดน้ำสามพันนาม",
    locationName: "ประจวบคีรีขันธ์",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ตลาดน้ำ","ย้อนยุค","ครอบครัว"],
    regionId: "central",
    provinceId: "prachuap-khiri-khan",
    description: "ตลาดน้ำย้อนยุคในบรรยากาศร่มรื่น มีของกินอร่อยและการแสดงไทย พร้อมบริการนั่งรถไฟจิ๋วชมวิว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดน้ำสามพันนาม"
  },
  {
    title: "อุโมงค์ไม้ไผ่ วัดจุฬาภรณ์วนาราม",
    locationName: "นครนายก",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ป่าไผ่","ถ่ายรูป","ร่มรื่น"],
    regionId: "central",
    provinceId: "nakhon-nayok",
    description: "เส้นทางเดินประดับด้วยซุ้มไม้ไผ่ที่โค้งเข้าหากันอย่างสวยงาม ให้บรรยากาศคล้ายป่าไผ่ในญี่ปุ่น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุโมงค์ไม้ไผ่+วัดจุฬาภรณ์วนาราม"
  },
  // ── ภาคใต้ (SOUTH - 38 Places) ──
  {
    title: "หมอมูดง",
    locationName: "ภูเก็ต",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารใต้","มิชลิน","ซีฟู้ด"],
    regionId: "south",
    provinceId: "phuket",
    description: "ร้านอาหารใต้พื้นเมืองรสจัดจ้านระดับมิชลินบิบกูร์มองด์ที่ตั้งอยู่ท่ามกลางป่าชายเลนอันร่มรื่น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หมอมูดง"
  },
  {
    title: "ครัวโอม",
    locationName: "ภูเก็ต",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารใต้","ร้านอาหารแนะนำ","อาหารพื้นเมือง"],
    regionId: "south",
    provinceId: "phuket",
    description: "ร้านอาหารบรรยากาศอบอุ่นที่เชฟพิถีพิถันในการเลือกวัตถุดิบ โดดเด่นด้วยเมนูเอี่ยมต้อคั่วเกลือ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ครัวโอม"
  },
  {
    title: "สมุทร (Samut)",
    locationName: "ภูเก็ต",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ไฟน์ไดนิง","ซีฟู้ด","มิชลิน"],
    regionId: "south",
    provinceId: "phuket",
    description: "ไฟน์ไดนิงอาหารใต้ที่ยกระดับวัตถุดิบจากชาวประมงพื้นบ้านให้มีความร่วมสมัยและสร้างสรรค์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สมุทร+(Samut)"
  },
  {
    title: "Torry's Ice Cream",
    locationName: "ภูเก็ต",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ไอศกรีม","ชิโนโปรตุกีส","เมืองเก่า"],
    regionId: "south",
    provinceId: "phuket",
    description: "คาเฟ่ไอศกรีมโฮมเมดในอาคารเก่าสไตล์ชิโนโปรตุกีสที่ผสานรสชาติขนมพื้นเมืองภูเก็ตได้อย่างลงตัว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Torry's+Ice+Cream"
  },
  {
    title: "ดินแดงดอย",
    locationName: "กระบี่",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ทะเลหมอก","จุดชมวิว","ภูเขา"],
    regionId: "south",
    provinceId: "krabi",
    description: "จุดชมวิวพระอาทิตย์ขึ้นและทะเลหมอกยามเช้าที่สวยงามตระการตาในจังหวัดกระบี่",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ดินแดงดอย"
  },
  {
    title: "หาดอ่าวนาง",
    locationName: "กระบี่",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ชายหาด","จุดชมวิว","ทะเลอันดามัน"],
    regionId: "south",
    provinceId: "krabi",
    description: "ชายหาดชื่อดังที่มีทิวทัศน์ภูเขาหินปูนโดดเด่นและเป็นจุดศูนย์กลางการท่องเที่ยวทางทะเลที่สำคัญ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดอ่าวนาง"
  },
  {
    title: "Into The Forest",
    locationName: "กระบี่",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่ป่า","วิวภูเขา","ธรรมชาติ"],
    regionId: "south",
    provinceId: "krabi",
    description: "คาเฟ่บรรยากาศสวนยางที่โอบล้อมด้วยหน้าผาและภูเขาหินปูนสุดอลังการ เหมาะแก่การถ่ายภาพ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Into+The+Forest"
  },
  {
    title: "Oasis Homemade Café",
    locationName: "พังงา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่สวน","วิวภูเขา","เบเกอรี่โฮมเมด"],
    regionId: "south",
    provinceId: "phang-nga",
    description: "คาเฟ่ร่มรื่นในสวนต้นไม้ที่สามารถมองเห็นวิวภูเขาสูงตระหง่านของเมืองพังงาได้อย่างชัดเจน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Oasis+Homemade+Café"
  },
  {
    title: "THE EIGHTH ROOM CAFE'",
    locationName: "พังงา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["สไตล์ลอฟต์","เขาหลัก","ร้านกาแฟ"],
    regionId: "south",
    provinceId: "phang-nga",
    description: "จุดเช็คอินสไตล์ลอฟต์ยอดฮิตในเขาหลักที่เสิร์ฟกาแฟสดและเค้กอบใหม่ทุกวัน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=THE+EIGHTH+ROOM+CAFE'"
  },
  {
    title: "DAY & NIGHT of Surat Thani",
    locationName: "สุราษฎร์ธานี",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["บาร์ดนตรีสด","แฮงเอาท์","คาเฟ่กลางคืน"],
    regionId: "south",
    provinceId: "surat-thani",
    description: "ร้านสไตล์ฮิปที่ช่วงกลางวันเปิดเป็นคาเฟ่และแปลงโฉมเป็นบาร์ดนตรีสดยามค่ำคืน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=DAY+&+NIGHT+of+Surat+Thani"
  },
  {
    title: "Cafe De Pier",
    locationName: "สุราษฎร์ธานี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่ริมทะเล","จุดถ่ายรูป","พักผ่อน"],
    regionId: "south",
    provinceId: "surat-thani",
    description: "ร้านกาแฟริมทะเลบรรยากาศชิลพร้อมสะพานไม้ทอดยาวให้เดินรับลมชมวิวอ่าวไทย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Cafe+De+Pier"
  },
  {
    title: "หาดหินงาม",
    locationName: "นครศรีธรรมราช",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดหิน","เล่นเซิร์ฟ","สิชล"],
    regionId: "south",
    provinceId: "nakhon-si-thammarat",
    description: "ชายหาดที่โดดเด่นด้วยโขดหินสวยงามและเริ่มเป็นที่นิยมสำหรับกิจกรรมทางน้ำอย่างเซิร์ฟบอร์ด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดหินงาม"
  },
  {
    title: "Blue Surf by Sichon Cabana",
    locationName: "นครศรีธรรมราช",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่ริมหาด","เซิร์ฟคลับ","จุดชมพระอาทิตย์ตก"],
    regionId: "south",
    provinceId: "nakhon-si-thammarat",
    description: "คาเฟ่ริมทะเลสุดชิลสำหรับสายเซิร์ฟที่เสิร์ฟเครื่องดื่มสดชื่นยามเย็นริมหาดสิชล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Blue+Surf+by+Sichon+Cabana"
  },
  {
    title: "โกปี๊ 1942",
    locationName: "นครศรีธรรมราช",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["บะกุ๊ดเต๋","กาแฟโบราณ","อาหารเช้า"],
    regionId: "south",
    provinceId: "nakhon-si-thammarat",
    description: "ร้านอาหารระดับตำนานของเมืองคอนที่ขึ้นชื่อเรื่องบะกุ๊ดเต๋และกาแฟโบราณรสชาติดั้งเดิม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=โกปี๊+1942"
  },
  {
    title: "ถ้ำมรกต",
    locationName: "ตรัง",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ถ้ำทะเล","อันซีนไทยแลนด์","ผจญภัย"],
    regionId: "south",
    provinceId: "trang",
    description: "สิ่งมหัศจรรย์ทางธรรมชาติที่นักท่องเที่ยวต้องลอยตัวผ่านความมืดเพื่อพบกับหาดทรายที่ซ่อนอยู่ภายใน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถ้ำมรกต"
  },
  {
    title: "เกาะกระดาน",
    locationName: "ตรัง",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดทรายขาว","ดำน้ำตื้น","ทะเลอันดามัน"],
    regionId: "south",
    provinceId: "trang",
    description: "เกาะที่ขึ้นชื่อว่ามีชายหาดที่สวยที่สุดในโลกพร้อมน้ำทะเลใสและแนวปะการังที่อุดมสมบูรณ์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เกาะกระดาน"
  },
  {
    title: "GRAY 18 CAFE",
    locationName: "ตรัง",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["สเปเชียลตี้คอฟฟี่","โรงคั่วกาแฟ","มินิมอล"],
    regionId: "south",
    provinceId: "trang",
    description: "คาเฟ่สไตล์เอิร์ธโทนสุดเท่ที่คัดสรรและคั่วเมล็ดกาแฟเองเพื่อสร้างรสชาติที่เป็นเอกลักษณ์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=GRAY+18+CAFE"
  },
  {
    title: "เกาะหลีเป๊ะ",
    locationName: "สตูล",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ดำน้ำ","ทะเลมัลดีฟส์เมืองไทย","เกาะ"],
    regionId: "south",
    provinceId: "satun",
    description: "เกาะสวรรค์แห่งอันดามันใต้ที่โดดเด่นด้วยทรายขาวละเอียดและจุดดำน้ำตื้นระดับโลก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เกาะหลีเป๊ะ"
  },
  {
    title: "MaBara Cafe",
    locationName: "สตูล",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่ริมทะเล","พระอาทิตย์ตก","ปากบารา"],
    regionId: "south",
    provinceId: "satun",
    description: "คาเฟ่ติดชายหาดบริเวณปากบาราที่เป็นจุดชมพระอาทิตย์ตกที่สวยงามที่สุดแห่งหนึ่งของจังหวัด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=MaBara+Cafe"
  },
  {
    title: "บิ้งนา คาเฟ่",
    locationName: "พัทลุง",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่ทุ่งนา","สะพานไม้","ธรรมชาติ"],
    regionId: "south",
    provinceId: "phatthalung",
    description: "ร้านกาแฟกลางทุ่งนาที่ให้คุณได้สัมผัสธรรมชาติอย่างใกล้ชิดผ่านการเดินบนสะพานไม้ทอดยาว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=บิ้งนา+คาเฟ่"
  },
  {
    title: "Rong Khua Kafae Suan Phai",
    locationName: "พัทลุง",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["โรงคั่วกาแฟ","ทำกาแฟเอง","สวนไผ่"],
    regionId: "south",
    provinceId: "phatthalung",
    description: "โรงคั่วกาแฟกลางสวนไผ่ที่ให้ลูกค้าได้ทดลองคั่วและบดเมล็ดกาแฟด้วยตัวเองในบรรยากาศร่มรื่น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Rong+Khua+Kafae+Suan+Phai"
  },
  {
    title: "Alive ชีวิตชีวา",
    locationName: "สงขลา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["บ้านต้นไม้","ธรรมชาติ","ถ่ายรูปสวย"],
    regionId: "south",
    provinceId: "songkhla",
    description: "คาเฟ่รูปแบบบ้านต้นไม้ที่รายล้อมด้วยธรรมชาติและมีมุมพักผ่อนบนเปลตาข่ายสุดชิล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Alive+ชีวิตชีวา"
  },
  {
    title: "Post Laser Disc Pub",
    locationName: "สงขลา",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["ผับหาดใหญ่","ดนตรีสด","นั่งดื่ม"],
    regionId: "south",
    provinceId: "songkhla",
    description: "ผับและบาร์ระดับตำนานใจกลางหาดใหญ่ที่โดดเด่นด้วยดนตรีสดและบรรยากาศการดื่มสุดคลาสสิก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Post+Laser+Disc+Pub"
  },
  {
    title: "Pattern Cozy Bar",
    locationName: "สงขลา",
    category: "สถานบันเทิง",
    iconName: "PartyPopper",
    tags: ["บาร์ลับ","นั่งชิล","หาดใหญ่กลางคืน"],
    regionId: "south",
    provinceId: "songkhla",
    description: "บาร์ลับนั่งชิลย่านราษฎร์ยินดีที่เหมาะสำหรับการแฮงเอาท์ในบรรยากาศเป็นกันเองและผ่อนคลาย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Pattern+Cozy+Bar"
  },
  {
    title: "มัสยิดกรือเซะ",
    locationName: "ปัตตานี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ประวัติศาสตร์","สถาปัตยกรรมอิสลาม","โบราณสถาน"],
    regionId: "south",
    provinceId: "pattani",
    description: "โบราณสถานทางประวัติศาสตร์ที่สำคัญซึ่งมีสถาปัตยกรรมอิสลามผสมผสานอันทรงคุณค่า",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=มัสยิดกรือเซะ"
  },
  {
    title: "ศาลเจ้าแม่ลิ้มกอเหนี่ยว",
    locationName: "ปัตตานี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ศาลเจ้า","วัฒนธรรมจีน","ความเชื่อ"],
    regionId: "south",
    provinceId: "pattani",
    description: "ศูนย์รวมจิตใจของชาวไทยเชื้อสายจีนในปัตตานีที่มีสถาปัตยกรรมศาลเจ้าที่งดงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ศาลเจ้าแม่ลิ้มกอเหนี่ยว"
  },
  {
    title: "Once Upon A Time Café",
    locationName: "ปัตตานี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ตู้คอนเทนเนอร์","คาเฟ่ปัตตานี","สไตล์ลอฟต์"],
    regionId: "south",
    provinceId: "pattani",
    description: "คาเฟ่ที่นำตู้คอนเทนเนอร์มาตกแต่งใหม่ในโทนสีละมุนพร้อมมุมถ่ายรูปเก๋ไก๋มากมาย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Once+Upon+A+Time+Café"
  },
  {
    title: "CLOVE Cafe",
    locationName: "ยะลา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["คาเฟ่เกาหลี","มินิมอล","ถ่ายรูปสวย"],
    regionId: "south",
    provinceId: "yala",
    description: "คาเฟ่สองชั้นที่ผสมผสานสไตล์มินิมอลคลีนๆ เข้ากับความเป็นเกาหลีสีชมพูหวานสดใส",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=CLOVE+Cafe"
  },
  {
    title: "ทะเลหมอกอัยเยอร์เวง",
    locationName: "ยะลา",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ทะเลหมอก","สกายวอล์ค","เบตง"],
    regionId: "south",
    provinceId: "yala",
    description: "จุดชมวิวยอดฮิตบนสกายวอล์คในอำเภอเบตงที่สามารถมองเห็นทะเลหมอกหนาทึบปกคลุมขุนเขา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ทะเลหมอกอัยเยอร์เวง"
  },
  {
    title: "ทะเลหมอกสุคิริน",
    locationName: "นราธิวาส",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ทะเลหมอก","สุคิริน","ธรรมชาติ"],
    regionId: "south",
    provinceId: "narathiwat",
    description: "จุดสัมผัสความหนาวเย็นและทะเลหมอกอลังการในพื้นที่ป่าอุดมสมบูรณ์ของชายแดนใต้",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ทะเลหมอกสุคิริน"
  },
  {
    title: "หาดนราทัศน์",
    locationName: "นราธิวาส",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดทราย","ปิกนิก","ทะเลอ่าวไทย"],
    regionId: "south",
    provinceId: "narathiwat",
    description: "ชายหาดที่ทอดยาวขนานกับทิวสนเขียวขจี เหมาะแก่การพักผ่อนและปิกนิกริมทะเลกับครอบครัว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดนราทัศน์"
  },
  {
    title: "มัสยิดวาดีลฮูเซ็น",
    locationName: "นราธิวาส",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["มัสยิดไม้","ประวัติศาสตร์","สถาปัตยกรรมมลายู"],
    regionId: "south",
    provinceId: "narathiwat",
    description: "มัสยิดเก่าแก่อายุ 300 ปีที่สร้างด้วยไม้ตะเคียนแบบสถาปัตยกรรมพื้นถิ่นมลายูโดยไม่ใช้ตะปู",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=มัสยิดวาดีลฮูเซ็น"
  },
  {
    title: "Thamsing Cafe",
    locationName: "ชุมพร",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["จุดชมวิว","พาโนรามา","กาแฟสด"],
    regionId: "south",
    provinceId: "chumphon",
    description: "คาเฟ่บนจุดชมวิวเขามัทรีที่เปิดโอกาสให้ลูกค้ามองเห็นทิวทัศน์ทะเลและภูเขาแบบพาโนรามา 360 องศา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Thamsing+Cafe"
  },
  {
    title: "คลองหินดำ",
    locationName: "ชุมพร",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["แกรนด์แคนยอน","ธรณีวิทยา","แหล่งน้ำธรรมชาติ"],
    regionId: "south",
    provinceId: "chumphon",
    description: "แกรนด์แคนยอนเมืองไทยที่เกิดจากรอยเลื่อนของเปลือกโลก มีกระแสน้ำใสไหลผ่านช่องหิน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=คลองหินดำ"
  },
  {
    title: "ปากน้ำตะโก",
    locationName: "ชุมพร",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["หมู่บ้านประมง","วิถีชีวิต","วัฒนธรรมท้องถิ่น"],
    regionId: "south",
    provinceId: "chumphon",
    description: "หมู่บ้านชาวประมงพื้นบ้านที่ยังคงรักษาวิถีชีวิตดั้งเดิมและสถาปัตยกรรมผสมผสานไทย-จีน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ปากน้ำตะโก"
  },
  {
    title: "Mata Cafe",
    locationName: "ระนอง",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["มินิมอล","วีแกน","โฮมเมด"],
    regionId: "south",
    provinceId: "ranong",
    description: "คาเฟ่สไตล์มินิมอลโทนสีขาวที่ดัดแปลงจากบ้านครึ่งปูนครึ่งไม้ เสิร์ฟเครื่องดื่มและขนมสูตรวีแกน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Mata+Cafe"
  },
  {
    title: "บ่อน้ำร้อนรักษะวาริน",
    locationName: "ระนอง",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำพุร้อน","สุขภาพ","ออนเซ็น"],
    regionId: "south",
    provinceId: "ranong",
    description: "แหล่งน้ำพุร้อนธรรมชาติใจกลางเมืองระนองที่เหมาะสำหรับการแช่น้ำแร่เพื่อการบำบัดและสุขภาพ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=บ่อน้ำร้อนรักษะวาริน"
  },
  {
    title: "168 Cafe Ranong",
    locationName: "ระนอง",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["โมเดิร์นทรอปิคอล","ใจกลางเมือง","เบเกอรี่"],
    regionId: "south",
    provinceId: "ranong",
    description: "คาเฟ่ใจกลางเมืองที่ตกแต่งในสไตล์โมเดิร์นทรอปิคอลที่ให้ความรู้สึกผ่อนคลายและหรูหรา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=168+Cafe+Ranong"
  },

  // ── ภาคตะวันตก (WEST - 40 Places) ──
  {
    title: "น้ำตกเอราวัณ",
    locationName: "กาญจนบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตก", "เล่นน้ำ", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "น้ำตกหินปูนสีเขียวมรกต 7 ชั้นที่เป็นสัญลักษณ์ของความงามทางธรรมชาติในอุทยานแห่งชาติเอราวัณ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกเอราวัณ"
  },
  {
    title: "สะพานมอญ",
    locationName: "กาญจนบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["สะพานไม้", "วิถีมอญ", "วัฒนธรรม"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "สะพานไม้ที่ยาวที่สุดในประเทศไทย เชื่อมวิถีชีวิตชาวไทยและชาวมอญในสังขละบุรีท่ามกลางสายหมอก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สะพานมอญ"
  },
  {
    title: "Skywalk กาญจนบุรี",
    locationName: "กาญจนบุรี",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["จุดชมวิว", "กระจกใส", "แลนด์มาร์ค"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "แลนด์มาร์คใหม่ริมแม่น้ำสองสีบนทางเดินกระจกใสที่ให้มุมมองพาโนรามาของเมืองกาญจนบุรี",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Skywalk+กาญจนบุรี"
  },
  {
    title: "ถ้ำกระแซ",
    locationName: "กาญจนบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["รถไฟสายมรณะ", "ประวัติศาสตร์", "ถ้ำ"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "จุดชมวิวเลียบหน้าผาบนเส้นทางรถไฟสายมรณะที่มีความสวยงามและประวัติศาสตร์ที่น่าจดจำ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถ้ำกระแซ"
  },
  {
    title: "น้ำตกห้วยแม่ขมิ้น",
    locationName: "กาญจนบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตก", "กางเต็นท์", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "น้ำตกหินปูนที่สวยงามราวกับภาพวาดในอุทยานแห่งชาติเขื่อนศรีนครินทร์ เดินทางเข้าถึงง่าย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกห้วยแม่ขมิ้น"
  },
  {
    title: "วัดถ้ำเสือ",
    locationName: "กาญจนบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดสวย", "จุดชมวิว", "พระใหญ่"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "วัดบนยอดเขาที่มีพระพุทธรูปองค์ใหญ่ที่สุดในจังหวัดกาญจนบุรีและวิวทุ่งนาที่กว้างไกล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดถ้ำเสือ"
  },
  {
    title: "คีรีธารา",
    locationName: "กาญจนบุรี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ริมน้ำแคว", "อาหารไทย", "บรรยากาศ"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "ร้านอาหารริมแม่น้ำแควที่มีบรรยากาศโรแมนติกและรสชาติอาหารไทยพื้นบ้านที่ได้รับรางวัล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=คีรีธารา"
  },
  {
    title: "Kan Machi Cafe",
    locationName: "กาญจนบุรี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ญี่ปุ่น", "ถ่ายรูป", "ของหวาน"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "คาเฟ่ธีมญี่ปุ่นที่จำลองบรรยากาศสวนและเสาโทริอิสีแดงมาไว้อย่างประณีต",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Kan+Machi+Cafe"
  },
  {
    title: "สวนสัตว์เปิด ซาฟารี ปาร์ค",
    locationName: "กาญจนบุรี",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["สวนสัตว์", "ครอบครัว", "ยีราฟ"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "สวนสัตว์เปิดที่ให้นักท่องเที่ยวได้สัมผัสสัตว์ป่าอย่างใกล้ชิดและถ่ายภาพกับยีราฟบนรถ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สวนสัตว์เปิด+ซาฟารี+ปาร์ค"
  },
  {
    title: "ต้นจามจุรียักษ์",
    locationName: "กาญจนบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ต้นไม้ใหญ่", "ร่มรื่น", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "kanchanaburi",
    description: "ต้นไม้ขนาดใหญ่อายุกกว่าร้อยปีที่มีพุ่มแผ่กว้างให้ร่มเงาครอบคลุมพื้นที่กว้างขวาง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ต้นจามจุรียักษ์"
  },
  {
    title: "น้ำตกทีลอซู",
    locationName: "ตาก",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตกใหญ่", "เดินป่า", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "tak",
    description: "มหาศาลแห่งสายน้ำที่ยิ่งใหญ่ที่สุดในประเทศไทย ตั้งอยู่ในเขตรักษาพันธุ์สัตว์ป่าอุ้มผาง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกทีลอซู"
  },
  {
    title: "วัดไทยวัฒนาราม",
    locationName: "ตาก",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ศิลปะพม่า", "วัดสวย", "แม่สอด"],
    regionId: "west",
    provinceId: "tak",
    description: "วัดที่งดงามด้วยสถาปัตยกรรมแบบพม่าสีทองอร่ามและพระพุทธมหามุนีจำลองที่ศักดิ์สิทธิ์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดไทยวัฒนาราม"
  },
  {
    title: "เถียงนา คอฟฟี่",
    locationName: "ตาก",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ครัวซองต์", "คาเฟ่ดัง", "เบเกอรี่"],
    regionId: "west",
    provinceId: "tak",
    description: "คาเฟ่ที่โด่งดังระดับประเทศด้วยครัวซองต์รสชาติพรีเมียมและบรรยากาศร้านที่ร่มรื่น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เถียงนา+คอฟฟี่"
  },
  {
    title: "น้ำตกปิตุ๊โกร",
    locationName: "ตาก",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["รูปหัวใจ", "เดินป่า", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "tak",
    description: "น้ำตกรูปหัวใจบนดอยมะม่วงสามหมื่น เป็นเส้นทางเดินป่าที่ท้าทายและมีความสวยงามสูง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกปิตุ๊โกร"
  },
  {
    title: "ศาลสมเด็จพระเจ้าตากสินมหาราช",
    locationName: "ตาก",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ประวัติศาสตร์", "ศักดิ์สิทธิ์", "วัฒนธรรม"],
    regionId: "west",
    provinceId: "tak",
    description: "สถานที่สำคัญคู่บ้านคู่เมืองตากเพื่อกราบไหว้ขอพรและรำลึกถึงพระมหากรุณาธิคุณ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ศาลสมเด็จพระเจ้าตากสินมหาราช"
  },
  {
    title: "ร้านชิดชล",
    locationName: "ตาก",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ริมแม่น้ำปิง", "อาหารไทย", "ร้านเก่าแก่"],
    regionId: "west",
    provinceId: "tak",
    description: "ร้านอาหารริมแม่น้ำปิงบรรยากาศดีที่มีเมนูอาหารไทยรสชาติดั้งเดิมที่เปิดมานาน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ร้านชิดชล"
  },
  {
    title: "สะพานแขวนสมโภช 200 ปี",
    locationName: "ตาก",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["จุดชมวิว", "ริมน้ำปิง", "สะพานแขวน"],
    regionId: "west",
    provinceId: "tak",
    description: "สะพานแขวนไม้ข้ามแม่น้ำปิงที่เป็นจุดพักผ่อนและชมวิวพระอาทิตย์ตกกลางเมืองตาก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สะพานแขวนสมโภช+200+ปี"
  },
  {
    title: "ตลาดน้ำดำเนินสะดวก",
    locationName: "ราชบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ตลาดน้ำ", "วิถีชีวิต", "วัฒนธรรม"],
    regionId: "west",
    provinceId: "ratchaburi",
    description: "ตลาดน้ำที่มีชีวิตชีวาและสะท้อนภาพการค้าขายทางเรือที่เป็นเอกลักษณ์ของไทยมาอย่างยาวนาน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตลาดน้ำดำเนินสะดวก"
  },
  {
    title: "อุทยานหินเขางู",
    locationName: "ราชบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ภูเขาหิน", "ถ่ายรูป", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "ratchaburi",
    description: "แหล่งท่องเที่ยวเชิงธรณีวิทยาที่เปลี่ยนจากเหมืองหินเก่าเป็นสวนสาธารณะที่มีวิวภูเขาสวยงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานหินเขางู"
  },
  {
    title: "Coro Field",
    locationName: "ราชบุรี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["เมล่อน", "ญี่ปุ่น", "คาเฟ่"],
    regionId: "west",
    provinceId: "ratchaburi",
    description: "ฟาร์มท่องเที่ยวสไตล์ญี่ปุ่นในสวนผึ้งที่โดดเด่นด้วยเมล่อนสายพันธุ์พิเศษและบรรยากาศมินิมอล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Coro+Field"
  },
  {
    title: "Alpaca Hill",
    locationName: "ราชบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["อัลปาก้า", "ฟาร์มสัตว์", "ครอบครัว"],
    regionId: "west",
    provinceId: "ratchaburi",
    description: "สวนสัตว์เปิดแนวฟาร์มที่ให้นักท่องเที่ยวได้สัมผัสและให้อาหารอัลปาก้าท่ามกลางธรรมชาติขุนเขา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Alpaca+Hill"
  },
  {
    title: "ครัวม่อนไข่",
    locationName: "ราชบุรี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารไทย", "สวนผึ้ง", "ยำผักกูด"],
    regionId: "west",
    provinceId: "ratchaburi",
    description: "ร้านอาหารชื่อดังในสวนผึ้งที่ขึ้นชื่อเรื่องยำผักกูดและเมนูอาหารไทยจากวัตถุดิบท้องถิ่น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ครัวม่อนไข่"
  },
  {
    title: "พิพิธภัณฑสถานแห่งชาติราชบุรี",
    locationName: "ราชบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ประวัติศาสตร์", "พิพิธภัณฑ์", "วัฒนธรรม"],
    regionId: "west",
    provinceId: "ratchaburi",
    description: "อาคารเก่าแก่สีชมพูที่จัดแสดงเรื่องราวประวัติศาสตร์และศิลปะพื้นบ้านของเมืองราชบุรี",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พิพิธภัณฑสถานแห่งชาติราชบุรี"
  },
  {
    title: "Oliva View De'Cafe",
    locationName: "ราชบุรี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["วิวภูเขา", "ถ่ายรูปสวย", "คาเฟ่"],
    regionId: "west",
    provinceId: "ratchaburi",
    description: "คาเฟ่สวนผึ้งวิวภูเขาที่ตกแต่งด้วยต้นมะกอกอายุกกว่าร้อยปี ให้บรรยากาศเหมือนอยู่ยุโรป",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Oliva+View+De'Cafe"
  },
  {
    title: "อุทยานแห่งชาติแก่งกระจาน",
    locationName: "เพชรบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["มรดกโลก", "เดินป่า", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "phetchaburi",
    description: "ป่ามรดกโลกที่มีความอุดมสมบูรณ์ทางชีวภาพและมีจุดชมวิวทะเลหมอกพะเนินทุ่งที่งดงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานแห่งชาติแก่งกระจาน"
  },
  {
    title: "พระนครคีรี (เขาวัง)",
    locationName: "เพชรบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ประวัติศาสตร์", "จุดชมวิว", "วัฒนธรรม"],
    regionId: "west",
    provinceId: "phetchaburi",
    description: "พระราชวังบนยอดเขาที่เป็นสถาปัตยกรรมผสมผสานไทย-ยุโรป-จีน แลนด์มาร์คสำคัญของจังหวัด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=พระนครคีรี+(เขาวัง)"
  },
  {
    title: "หาดชะอำ",
    locationName: "เพชรบุรี",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["เล่นน้ำ", "เจ็ตสกี", "ทะเล"],
    regionId: "west",
    provinceId: "phetchaburi",
    description: "ชายหาดยอดนิยมที่มีกิจกรรมทางน้ำหลากหลายและร้านอาหารทะเลสดๆ เรียงรายริมชายหาด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดชะอำ"
  },
  {
    title: "ถ้ำเขาหลวง",
    locationName: "เพชรบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["แสงลอดถ้ำ", "ไหว้พระ", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "phetchaburi",
    description: "ถ้ำหินปูนที่ประดิษฐานพระพุทธรูปสำคัญ มีแสงธรรมชาติลอดปล่องถ้ำลงมาอย่างงดงาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถ้ำเขาหลวง"
  },
  {
    title: "Camel Republic",
    locationName: "เพชรบุรี",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["สวนอูฐ", "สวนสนุก", "ถ่ายรูป"],
    regionId: "west",
    provinceId: "phetchaburi",
    description: "สวนสัตว์และสวนสนุกธีมโมร็อกโกที่ตกแต่งด้วยอาคารสีส้มสดใสและกิจกรรมขี่อูฐ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Camel+Republic"
  },
  {
    title: "ร้านสังเวียนซีฟู้ด",
    locationName: "เพชรบุรี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารทะเล", "ริมหาด", "ของสด"],
    regionId: "west",
    provinceId: "phetchaburi",
    description: "ร้านอาหารทะเลเจ้าดังริมชายหาดชะอำที่เสิร์ฟอาหารทะเลสดใหม่ในราคาที่คุ้มค่า",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ร้านสังเวียนซีฟู้ด"
  },
  {
    title: "หาดปึกเตียน",
    locationName: "เพชรบุรี",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["รูปพรรณนางยักษ์", "วรรณคดีไทย", "ทะเล"],
    regionId: "west",
    provinceId: "phetchaburi",
    description: "ชายหาดที่มีเอกลักษณ์ด้วยรูปปั้นตัวละครจากวรรณคดีพระอภัยมณีขนาดใหญ่ริมทะเล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดปึกเตียน"
  },
  {
    title: "หาดหัวหิน",
    locationName: "ประจวบคีรีขันธ์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ชายหาด", "ขี่ม้า", "ทะเล"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "ชายหาดยอดนิยมระดับโลกที่ยังคงบรรยากาศคลาสสิกและเหมาะสำหรับการพักผ่อนแบบครอบครัว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดหัวหิน"
  },
  {
    title: "วัดห้วยมงคล",
    locationName: "ประจวบคีรีขันธ์",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["หลวงพ่อทวด", "ไหว้พระ", "วัฒนธรรม"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "ที่ประดิษฐานรูปเหมือนหลวงพ่อทวดองค์ใหญ่ที่สุดในโลก เป็นศูนย์รวมจิตใจของนักท่องเที่ยว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดห้วยมงคล"
  },
  {
    title: "Cicada Market",
    locationName: "ประจวบคีรีขันธ์",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["ตลาดนัดศิลปะ", "แฮนด์เมด", "ดนตรีสด"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "ตลาดนัดยามค่ำคืนในสวนที่เน้นงานศิลปะ สินค้าทำมือ และการแสดงดนตรีสดที่มีสไตล์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Cicada+Market"
  },
  {
    title: "Vana Nava Water Jungle",
    locationName: "ประจวบคีรีขันธ์",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["สวนน้ำ", "เครื่องเล่น", "ครอบครัว"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "สวนน้ำขนาดใหญ่ระดับโลกที่รวบรวมเครื่องเล่นสุดตื่นเต้นไว้ในบรรยากาศป่าเขตร้อน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Vana+Nava+Water+Jungle"
  },
  {
    title: "จุดชมวิวเขาหินเหล็กไฟ",
    locationName: "ประจวบคีรีขันธ์",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["จุดชมวิว", "ถ่ายรูป", "ธรรมชาติ"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "จุดชมวิวพาโนรามาที่สวยที่สุดในหัวหิน สามารถมองเห็นวิวเมืองและชายหาดได้ทั้งหมด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=จุดชมวิวเขาหินเหล็กไฟ"
  },
  {
    title: "อ่าวมะนาว",
    locationName: "ประจวบคีรีขันธ์",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ทะเลสวย", "กองบิน5", "น้ำใส"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "ชายหาดที่สวยงามและน้ำใสสะอาด ตั้งอยู่ภายในกองบิน 5 มีบรรยากาศที่เงียบสงบและปลอดภัย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อ่าวมะนาว"
  },
  {
    title: "อุดมโภชนา ปราณบุรี",
    locationName: "ประจวบคีรีขันธ์",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["อาหารทะเล", "ปราณบุรี", "ปลาหมึกแดดเดียว"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "ร้านอาหารทะเลดั้งเดิมริมหาดปราณบุรีที่ขึ้นชื่อเรื่องความสดและปลาหมึกแดดเดียวรสเด็ด",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุดมโภชนา+ปราณบุรี"
  },
  {
    title: "Drip Rim Lay",
    locationName: "ประจวบคีรีขันธ์",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["กาแฟดริป", "ริมหาด", "คาเฟ่"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "คาเฟ่ริมทะเลหัวหินที่เน้นกาแฟดริป Specialty Coffee ในบรรยากาศที่เรียบง่ายและเป็นธรรมชาติ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Drip+Rim+Lay"
  },
  {
    title: "อุทยานราชภักดิ์",
    locationName: "ประจวบคีรีขันธ์",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["อนุสาวรีย์", "ประวัติศาสตร์", "วัฒนธรรม"],
    regionId: "west",
    provinceId: "prachuap-khiri-khan",
    description: "อุทยานประวัติศาสตร์ที่ประดิษฐานพระบรมราชานุสาวรีย์ของบูรพกษัตริย์ไทย 7 พระองค์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานราชภักดิ์"
  },

  // ── ภาคตะวันออก (EAST - 37 Places) ──
  {
    title: "เกาะล้าน",
    locationName: "ชลบุรี",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["เกาะ", "ดำน้ำ", "ทะเลใกล้กรุง"],
    regionId: "east",
    provinceId: "chon-buri",
    description: "สวรรค์ทะเลอ่าวไทยใกล้กรุงเทพฯ โดดเด่นด้วยน้ำทะเลใสและระบบนิเวศปะการังที่เหมาะแก่การดำน้ำตื้น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เกาะล้าน"
  },
  {
    title: "ถนนคนเดินพัทยา",
    locationName: "ชลบุรี",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["ไนต์คลับ", "พัทยา", "ปาร์ตี้"],
    regionId: "east",
    provinceId: "chon-buri",
    description: "ศูนย์กลางความบันเทิงยามราตรีระดับโลกที่คึกคักไปด้วยแสงสีและสถานบันเทิงที่เปิดให้บริการจนถึงตีสาม",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถนนคนเดินพัทยา"
  },
  {
    title: "ถ้ำบีชคลับ",
    locationName: "ชลบุรี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ริมทะเล", "บีชคลับ", "ถ่ายรูป"],
    regionId: "east",
    provinceId: "chon-buri",
    description: "คาเฟ่ริมหาดพัทยาสไตล์บาหลีที่ให้บรรยากาศสุดชิลพร้อมมุมถ่ายรูปที่งดงามและการออกแบบสถาปัตยกรรมที่โดดเด่น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ถ้ำบีชคลับ"
  },
  {
    title: "สวนไดโนเสาร์พัทยา",
    locationName: "ชลบุรี",
    category: "สถานบันเทิง",
    iconName: "Ticket",
    tags: ["สวนสนุก", "ไดโนเสาร์", "ครอบครัว"],
    regionId: "east",
    provinceId: "chon-buri",
    description: "อาณาจักรไดโนเสาร์เสมือนจริงที่รวบรวมสายพันธุ์ล้านปีกกว่า 100 ชนิดให้ครอบครัวได้ผจญภัยพร้อมกิจกรรมแบบอินเทอร์แอคทีฟ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=สวนไดโนเสาร์พัทยา"
  },
  {
    title: "หาดวอนนภา",
    locationName: "ชลบุรี",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ชายหาด", "บางแสน", "นั่งชิล"],
    regionId: "east",
    provinceId: "chon-buri",
    description: "ชายหาดที่เงียบสงบกว่าบางแสน เป็นแหล่งพักผ่อนยอดนิยมที่รายล้อมด้วยร้านอาหารและสตรีทฟู้ดริมทะเล",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หาดวอนนภา"
  },
  {
    title: "ทุ่งโปรงทอง",
    locationName: "ระยอง",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ป่าชายเลน", "สะพานไม้", "จุดชมวิว"],
    regionId: "east",
    provinceId: "rayong",
    description: "ผืนป่าชายเลนสีทองอร่ามที่มาพร้อมสะพานไม้ทอดยาวกว่า 2 กิโลเมตรให้เดินชมระบบนิเวศอันอุดมสมบูรณ์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ทุ่งโปรงทอง"
  },
  {
    title: "เกาะเสม็ด",
    locationName: "ระยอง",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["หาดทรายขาว", "เกาะ", "เล่นน้ำ"],
    regionId: "east",
    provinceId: "rayong",
    description: "เกาะอ่าวไทยที่ขึ้นชื่อเรื่องหาดทรายขาวเนียนละเอียดและรีสอร์ทที่พักหลากหลายสไตล์ที่ตอบโจทย์ทุกกลุ่มนักเดินทาง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เกาะเสม็ด"
  },
  {
    title: "ร้านป้ายาซีฟู้ด",
    locationName: "ระยอง",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ซีฟู้ด", "ริมหาด", "จัดจ้าน"],
    regionId: "east",
    provinceId: "rayong",
    description: "ร้านอาหารทะเลริมหาดที่เสิร์ฟวัตถุดิบสดใหม่จากเรือประมงพร้อมรสชาติน้ำจิ้มสุดจัดจ้านที่ครองใจนักท่องเที่ยว",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ร้านป้ายาซีฟู้ด"
  },
  {
    title: "มิราเคิล ออฟ เนเชอรัล",
    locationName: "ระยอง",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ดอกทิวลิป", "เมืองหนาว", "ถ่ายรูป"],
    regionId: "east",
    provinceId: "rayong",
    description: "โดมนิทรรศการจัดแสดงดอกทิวลิปและไม้เมืองหนาวที่ใช้นวัตกรรมความเย็นจากก๊าซธรรมชาติรักษาอุณหภูมิ 15 องศาเซลเซียส",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=มิราเคิล+ออฟ+เนเชอรัล"
  },
  {
    title: "เขาแหลมหญ้า",
    locationName: "ระยอง",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["กางเต็นท์", "อุทยาน", "พระอาทิตย์ตก"],
    regionId: "east",
    provinceId: "rayong",
    description: "อุทยานแห่งชาติที่มอบวิวทะเลแบบพาโนรามาและจุดกางเต็นท์รับลมทะเลที่สวยงามที่สุดแห่งหนึ่งของภาคตะวันออก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เขาแหลมหญ้า"
  },
  {
    title: "อาสนวิหารพระนางมารีอาปฏิสนธินิรมล",
    locationName: "จันทบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["โบสถ์คริสต์", "สถาปัตยกรรม", "ประวัติศาสตร์"],
    regionId: "east",
    provinceId: "chanthaburi",
    description: "โบสถ์คริสต์นิกายโรมันคาทอลิกสไตล์โกธิคอายุกว่าร้อยปีที่ประดับด้วยกระจกสีและมีความงดงามระดับประเทศ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อาสนวิหารพระนางมารีอาปฏิสนธินิรมล"
  },
  {
    title: "ชุมชนริมน้ำจันทบูร",
    locationName: "จันทบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["เมืองเก่า", "ริมน้ำ", "คลาสสิก"],
    regionId: "east",
    provinceId: "chanthaburi",
    description: "ชุมชนการค้าเก่าแก่ริมแม่น้ำที่อนุรักษ์สถาปัตยกรรมชิโนโปรตุกีสและวิถีชีวิตดั้งเดิมอย่างมีเสน่ห์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ชุมชนริมน้ำจันทบูร"
  },
  {
    title: "จุดชมวิวเนินนางพญา",
    locationName: "จันทบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["จุดชมวิว", "หน้าผา", "เลียบทะเล"],
    regionId: "east",
    provinceId: "chanthaburi",
    description: "จุดชมวิวถนนเลียบชายทะเลที่โค้งเลาะผาชัน มอบทัศนียภาพของทะเลอ่าวไทยที่สวยงามที่สุดแห่งหนึ่งของไทย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=จุดชมวิวเนินนางพญา"
  },
  {
    title: "น้ำตกพลิ้ว",
    locationName: "จันทบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตก", "ปลาพลวง", "ร่มรื่น"],
    regionId: "east",
    provinceId: "chanthaburi",
    description: "น้ำตกประวัติศาสตร์กลางป่าดิบชื้นที่ร่มรื่น เต็มไปด้วยฝูงปลาพลวงหินและอนุสรณ์สถานอลงกรณ์เจดีย์",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกพลิ้ว"
  },
  {
    title: "ไอศกรีมตราจรวด",
    locationName: "จันทบุรี",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["ของหวาน", "ไอศกรีม", "ตำนาน"],
    regionId: "east",
    provinceId: "chanthaburi",
    description: "โรงงานผลิตไอศกรีมด้วยเครื่องจักรแห่งแรกของเมืองจันท์ เสิร์ฟความหวานเย็นในตำนานกว่า 70 ปีคู่ชุมชน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ไอศกรีมตราจรวด"
  },
  {
    title: "เกาะช้าง",
    locationName: "ตราด",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["เกาะใหญ่", "ธรรมชาติ", "พักผ่อน"],
    regionId: "east",
    provinceId: "trat",
    description: "เกาะขนาดใหญ่ที่ผสมผสานความอุดมสมบูรณ์ของป่าไม้ดิบชื้น น้ำตก และชายหาดที่สวยงามรวมถึงหมู่บ้านชาวประมง",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เกาะช้าง"
  },
  {
    title: "เกาะกูด",
    locationName: "ตราด",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["มัลดีฟส์เมืองไทย", "เงียบสงบ", "น้ำใส"],
    regionId: "east",
    provinceId: "trat",
    description: "สวรรค์แห่งการพักผ่อนที่มีหาดทรายขาวละเอียดและน้ำทะเลใสกิ๊งราวกับคริสตัล พร้อมกิจกรรมพายคายัค",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เกาะกูด"
  },
  {
    title: "หมู่เกาะ r-ang",
    locationName: "ตราด",
    category: "ทะเล",
    iconName: "Waves",
    tags: ["ดำน้ำตื้น", "ปะการัง", "อุทยาน"],
    regionId: "east",
    provinceId: "trat",
    description: "แหล่งดำน้ำตื้นที่ดีที่สุดในทะเลตราด รายล้อมไปด้วยแนวปะการังที่สมบูรณ์และฝูงปลาหลากสีสัน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=หมู่เกาะ+r-ang"
  },
  {
    title: "ชุมชนบ้านน้ำเชี่ยว",
    locationName: "ตราด",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["เชิงนิเวศ", "วิถีชุมชน", "งอบ"],
    regionId: "east",
    provinceId: "trat",
    description: "ชุมชนต้นแบบการท่องเที่ยวเชิงนิเวศที่หลอมรวมวิถีชีวิตชาวพุทธและมุสลิมเข้าด้วยกันอย่างกลมกลืน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ชุมชนบ้านน้ำเชี่ยว"
  },
  {
    title: "บะหมี่เกี๊ยวหนองบัว",
    locationName: "ตราด",
    category: "อาหาร",
    iconName: "UtensilsCrossed",
    tags: ["บะหมี่โฮมเมด", "ร้านดัง", "ตำนาน"],
    regionId: "east",
    provinceId: "trat",
    description: "ร้านบะหมี่โฮมเมดระดับตำนานกว่า 50 ปีที่ยกระดับเมนูท้องถิ่นด้วยการตกแต่งร้านสไตล์จีนโมเดิร์น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=บะหมี่เกี๊ยวหนองบัว"
  },
  {
    title: "วัดโสธรวรารามวรวิหาร",
    locationName: "ฉะเชิงเทรา",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ไหว้พระ", "หลวงพ่อโสธร", "ขอพร"],
    regionId: "east",
    provinceId: "chachoengsao",
    description: "ศูนย์รวมจิตใจของชาวแปดริ้ว ประดิษฐานหลวงพ่อโสธรในพระอุโบสถหินอ่อนที่วิจิตรตระการตา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดโสธรวรารามวรวิหาร"
  },
  {
    title: "เรดแคทคาเฟ่ ตลาดบ้านใหม่",
    locationName: "ฉะเชิงเทรา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ริมแม่น้ำ", "ตลาดโบราณ", "ธีมแมว"],
    regionId: "east",
    provinceId: "chachoengsao",
    description: "คาเฟ่สุดคิวต์ริมแม่น้ำบางปะกงที่ตกแต่งด้วยธีมแมว มอบบรรยากาศสบายๆ ท่ามกลางตลาดโบราณ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เรดแคทคาเฟ่+ตลาดบ้านใหม่"
  },
  {
    title: "เอพริลคาเฟ่",
    locationName: "ฉะเชิงเทรา",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["ริมน้ำ", "ถ่ายรูป", "พักผ่อน"],
    regionId: "east",
    provinceId: "chachoengsao",
    description: "ร้านกาแฟริมน้ำดีไซน์น่ารักที่แบ่งสัดส่วนอย่างลงตัว ให้บริการทั้งเบเกอรี่และเครื่องดื่มรสละมุน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=เอพริลคาเฟ่"
  },
  {
    title: "มินิมูร่าห์ฟาร์ม",
    locationName: "ฉะเชิงเทรา",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ฟาร์มสัตว์", "ครอบครัว", "กิจกรรม"],
    regionId: "east",
    provinceId: "chachoengsao",
    description: "แหล่งท่องเที่ยวเชิงเกษตรที่ให้ผู้มาเยือนได้สัมผัสและป้อนอาหารสัตว์น่ารัก พร้อมกิจกรรมทำพิซซ่า",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=มินิมูร่าห์ฟาร์ม"
  },
  {
    title: "วัดเขาดิน",
    locationName: "ฉะเชิงเทรา",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["บนเขา", "สงบ", "จุดชมวิว"],
    regionId: "east",
    provinceId: "chachoengsao",
    description: "ศาสนสถานบนเนินเขาที่เงียบสงบ เปิดโอกาสให้ผู้มาเยือนได้สักการะสิ่งศักดิ์สิทธิ์และชมวิวแม่น้ำ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดเขาดิน"
  },
  {
    title: "ตึกเจ้าพระยาอภัยภูเบศร",
    locationName: "ปราจีนบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ตึกเหลือง", "สมุนไพร", "คลาสสิก"],
    regionId: "east",
    provinceId: "prachinburi",
    description: "อาคารสีเหลืองสไตล์ยุโรปอันทรงคุณค่าทางประวัติศาสตร์ ซึ่งเป็นศูนย์กลางการเรียนรู้ด้านแพทย์แผนไทย",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ตึกเจ้าพระยาอภัยภูเบศร"
  },
  {
    title: "แก่งหินเพิง",
    locationName: "ปราจีนบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ล่องแก่ง", "ผจญภัย", "หน้าฝน"],
    regionId: "east",
    provinceId: "prachinburi",
    description: "สถานที่ท้าทายความกล้าด้วยเส้นทางล่องแก่งระดับ 3-5 ท่ามกลางสายน้ำเชี่ยวในช่วงฤดูฝน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=แก่งหินเพิง"
  },
  {
    title: "วัดรัตนเนตรตาราม",
    locationName: "ปราจีนบุรี",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["วัดล้านหอย", "สถาปัตยกรรม", "อันซีน"],
    regionId: "east",
    provinceId: "prachinburi",
    description: "สถาปัตยกรรมทางพุทธศาสนาสุดอลังการที่สร้างสรรค์และประดับประดาด้วยเปลือกหอยนับล้านชิ้น",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดรัตนเนตรตาราม"
  },
  {
    title: "น้ำตกธารทิพย์",
    locationName: "ปราจีนบุรี",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["น้ำตก", "ป่าสมบูรณ์", "เล่นน้ำ"],
    regionId: "east",
    provinceId: "prachinburi",
    description: "สายน้ำตกที่ไหลลดหลั่นผ่านลานหินกว้างท่ามกลางป่าอุดมสมบูรณ์ เหมาะแก่การมาพักผ่อนหยือนใจ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=น้ำตกธารทิพย์"
  },
  {
    title: "คาเฟ่สวนไผ่ 33",
    locationName: "ปราจีนบุรี",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["สไตล์ญี่ปุ่น", "ป่าไผ่", "มัทฉะ"],
    regionId: "east",
    provinceId: "prachinburi",
    description: "คาเฟ่บรรยากาศญี่ปุ่นแบบดั้งเดิมที่ซ่อนตัวอยู่ในสวนไผ่ร่มรื่น พร้อมเสิร์ฟขนมและเครื่องดื่มมัทฉะ",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=คาเฟ่สวนไผ่+33"
  },
  {
    title: "ปราสาทสด๊กก๊อกธม",
    locationName: "สระแก้ว",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["ปราสาทหิน", "โบราณสถาน", "ขอม"],
    regionId: "east",
    provinceId: "sa-kaeo",
    description: "โบราณสถานขอมขนาดใหญ่ที่สุดในภาคตะวันออกที่สะท้อนถึงความรุ่งเรืองของอารยธรรมพันปี",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ปราสาทสด๊กก๊อกธม"
  },
  {
    title: "อุทยานแห่งชาติปางสีดา",
    locationName: "สระแก้ว",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["ดูผีเสื้อ", "ป่าดิบชื้น", "น้ำตก"],
    regionId: "east",
    provinceId: "sa-kaeo",
    description: "แหล่งท่องเที่ยวเชิงนิเวศที่มีชื่อเสียงระดับประเทศในการชมผีเสื้อหลากสีสันนับแสนตัวกลางป่าลึก",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=อุทยานแห่งชาติปางสีดา"
  },
  {
    title: "วู้ดเฮาส์ เขาฉกรรจ์",
    locationName: "สระแก้ว",
    category: "คาเฟ่",
    iconName: "Coffee",
    tags: ["วิวภูเขา", "ทุ่งดอกไม้", "ถ่ายรูป"],
    regionId: "east",
    provinceId: "sa-kaeo",
    description: "คาเฟ่ริมทุ่งดอกไม้กว้างใหญ่ที่มีภูเขาหินปูนเขาฉกรรจ์ตั้งตระหง่านเป็นฉากหลังสุดตระการตา",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วู้ดเฮาส์+เขาฉกรรจ์"
  },
  {
    title: "วัดแม่ย่าซอม",
    locationName: "สระแก้ว",
    category: "วัฒนธรรม",
    iconName: "Landmark",
    tags: ["สายมู", "พระราหู", "ขอพร"],
    regionId: "east",
    provinceId: "sa-kaeo",
    description: "ศูนย์รวมความศรัทธาของนักแสวงบุญและสายมู โดดเด่นด้วยองค์พระพิฆเนศและพระราหูขนาดใหญ่",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=วัดแม่ย่าซอม"
  },
  {
    title: "ละลุ",
    locationName: "สระแก้ว",
    category: "ธรรมชาติ",
    iconName: "TreePine",
    tags: ["แกรนด์แคนยอน", "ประติมากรรมธรรมชาติ", "อันซีน"],
    regionId: "east",
    provinceId: "sa-kaeo",
    description: "ประติมากรรมธรรมชาติที่เกิดจากการยุบตัวของดินจนกลายเป็นเสาหินทรายรูปร่างแปลกตาคล้ายแคนยอน",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=ละลุ"
  },
];

/**
 * Category label mapping for discovery chips (Thai).
 * Maps the original allResults keys to discovery chip labels used in UI.
 */
export const CATEGORY_CHIP_MAP: Record<string, string[]> = {
  'ธรรมชาติ': ['ธรรมชาติ', 'ป่าไม้'],
  'ทะเล': ['ทะเล'],
  'อาหาร': ['อาหาร', 'ของกิน'],
  'สถานบันเทิง': ['สถานบันเทิง'],
  'คาเฟ่': ['คาเฟ่'],
  'วัฒนธรรม': ['วัฒนธรรม'],
};
