export const POPULAR_PROVINCES_SEED = [
  // ── ภาคเหนือ (North - 17 Provinces) ──
  { province_id: 'chiangmai', province_name: 'Chiang Mai', region_id: 'north', visitor_count: 10500000, popularity_factors: 'Lanna Culture & Mountains, Digital Nomad Hub' },
  { province_id: 'chiangrai', province_name: 'Chiang Rai', region_id: 'north', visitor_count: 3500000, popularity_factors: 'White Temple, Golden Triangle' },
  { province_id: 'phitsanulok', province_name: 'Phitsanulok', region_id: 'north', visitor_count: 2800000, popularity_factors: 'Phra Phuttha Chinnarat, Historical Gateway' },
  { province_id: 'sukhothai', province_name: 'Sukhothai', region_id: 'north', visitor_count: 1500000, popularity_factors: 'Ancient Capital, UNESCO Heritage' },
  { province_id: 'maehongson', province_name: 'Mae Hong Son', region_id: 'north', visitor_count: 1200000, popularity_factors: 'Pai, Mist & Mountains' },
  { province_id: 'lampang', province_name: 'Lampang', region_id: 'north', visitor_count: 1100000, popularity_factors: 'Horse Carriages, Wat Phra That Lampang Luang' },
  { province_id: 'nan', province_name: 'Nan', region_id: 'north', visitor_count: 950000, popularity_factors: 'Slow Life, Bo Kluea, Temple Art' },
  { province_id: 'phetchabun', province_name: 'Phetchabun', region_id: 'north', visitor_count: 850000, popularity_factors: 'Khao Kho, Phu Thap Boek, Sea of Mist' },
  { province_id: 'nakhonsawan', province_name: 'Nakhon Sawan', region_id: 'north', visitor_count: 750000, popularity_factors: 'Origin of Chao Phraya, Dragon Festival' },
  { province_id: 'phrae', province_name: 'Phrae', region_id: 'north', visitor_count: 650000, popularity_factors: 'Phae Mueang Phi, Teak Wood Houses' },
  { province_id: 'phayao', province_name: 'Phayao', region_id: 'north', visitor_count: 580000, popularity_factors: 'Kwan Phayao Lake, Wat Tilok Aram' },
  { province_id: 'uttaradit', province_name: 'Uttaradit', region_id: 'north', visitor_count: 520000, popularity_factors: 'Long Lablae Durian, Sirikit Dam' },
  { province_id: 'kamphaengphet', province_name: 'Kamphaeng Phet', region_id: 'north', visitor_count: 480000, popularity_factors: 'Historical Park, Ban Kluai, Hot Springs' },
  { province_id: 'lamphun', province_name: 'Lamphun', region_id: 'north', visitor_count: 450000, popularity_factors: 'Hariphunchai Temple, Longan Orchards' },
  { province_id: 'uthaithani', province_name: 'Uthai Thani', region_id: 'north', visitor_count: 420000, popularity_factors: 'Wat Tha Sung, Huai Kha Khaeng' },
  { province_id: 'phichit', province_name: 'Phichit', region_id: 'north', visitor_count: 380000, popularity_factors: 'Wat Tha Luang, Boat Racing Tradition' },
  { province_id: 'chainat', province_name: 'Chai Nat', region_id: 'north', visitor_count: 350000, popularity_factors: 'Bird Park, Chao Phraya Dam' },

  // ── ภาคตะวันออกเฉียงเหนือ (Northeast/Isan - 20 Provinces) ──
  { province_id: 'nakhonratchasima', province_name: 'Nakhon Ratchasima', region_id: 'northeast', visitor_count: 7200000, popularity_factors: 'Khao Yai National Park, Phimai Historical Park' },
  { province_id: 'khonkaen', province_name: 'Khon Kaen', region_id: 'northeast', visitor_count: 4800000, popularity_factors: 'MICE City, Dino Discovery, Education Hub' },
  { province_id: 'udonthani', province_name: 'Udon Thani', region_id: 'northeast', visitor_count: 3100000, popularity_factors: 'Red Lotus Sea, Ban Chiang Museum' },
  { province_id: 'buriram', province_name: 'Buri Ram', region_id: 'northeast', visitor_count: 2500000, popularity_factors: 'Phanom Rung, Sports City, MotoGP' },
  { province_id: 'ubonratchathani', province_name: 'Ubon Ratchathani', region_id: 'northeast', visitor_count: 2200000, popularity_factors: 'Candle Festival, Pha Taem National Park' },
  { province_id: 'nongkhai', province_name: 'Nong Khai', region_id: 'northeast', visitor_count: 1800000, popularity_factors: 'Mekong River, Thai-Lao Friendship Bridge' },
  { province_id: 'roiet', province_name: 'Roi Et', region_id: 'northeast', visitor_count: 1600000, popularity_factors: 'Bung Phalan Chai, Roi Et Tower' },
  { province_id: 'loei', province_name: 'Loei', region_id: 'northeast', visitor_count: 1500000, popularity_factors: 'Chiang Khan, Phu Kradueng, Cool Climate' },
  { province_id: 'chaiyaphum', province_name: 'Chaiyaphum', region_id: 'northeast', visitor_count: 1300000, popularity_factors: 'Siam Tulip Fields, Mor Hin Khao' },
  { province_id: 'surin', province_name: 'Surin', region_id: 'northeast', visitor_count: 1200000, popularity_factors: 'Elephant Festival, Silverware, Silk' },
  { province_id: 'sisaket', province_name: 'Si Sa Ket', region_id: 'northeast', visitor_count: 1100000, popularity_factors: 'Pha Mo E Daeng, Khao Phra Wihan' },
  { province_id: 'sakonnakhon', province_name: 'Sakon Nakhon', region_id: 'northeast', visitor_count: 950000, popularity_factors: 'Wax Castle Festival, Indigo Cloth' },
  { province_id: 'nakhonphanom', province_name: 'Nakhon Phanom', region_id: 'northeast', visitor_count: 900000, popularity_factors: 'Phra That Phanom, Third Friendship Bridge' },
  { province_id: 'kalasin', province_name: 'Kalasin', region_id: 'northeast', visitor_count: 850000, popularity_factors: 'Dinosaur Museum, Praewa Silk' },
  { province_id: 'mahasarakham', province_name: 'Maha Sarakham', region_id: 'northeast', visitor_count: 800000, popularity_factors: 'Taksila of Isan, Education Center' },
  { province_id: 'mukdahan', province_name: 'Mukdahan', region_id: 'northeast', visitor_count: 750000, popularity_factors: 'Indochina Market, Phu Pha Thoep' },
  { province_id: 'yasothon', province_name: 'Yasothon', region_id: 'northeast', visitor_count: 700000, popularity_factors: 'Rocket Festival, Toad Museum' },
  { province_id: 'buengkan', province_name: 'Bueng Kan', region_id: 'northeast', visitor_count: 650000, popularity_factors: 'Three Whale Rocks, Wat Phu Thok' },
  { province_id: 'nongbualamphu', province_name: 'Nong Bua Lam Phu', region_id: 'northeast', visitor_count: 550000, popularity_factors: 'Shell Fossil Museum, Wat Tham Klong Phen' },
  { province_id: 'amnatcharoen', province_name: 'Amnat Charoen', region_id: 'northeast', visitor_count: 450000, popularity_factors: 'Phra Mongkhon Ming Mueang, Puttha Utthayan' },

  // ── ภาคกลาง (Central - 12 Provinces) ──
  { province_id: 'bangkok', province_name: 'Bangkok', region_id: 'central', visitor_count: 35000000, popularity_factors: 'Capital City, Shopping, Street Food, Grand Palace' },
  { province_id: 'ayutthaya', province_name: 'Phra Nakhon Si Ayutthaya', region_id: 'central', visitor_count: 8500000, popularity_factors: 'UNESCO Historical Park, Temples' },
  { province_id: 'nakhonpathom', province_name: 'Nakhon Pathom', region_id: 'central', visitor_count: 3000000, popularity_factors: 'Phra Pathom Chedi, Floating Markets, Cafes' },
  { province_id: 'nonthaburi', province_name: 'Nonthaburi', region_id: 'central', visitor_count: 2900000, popularity_factors: 'Koh Kret, Riverside Dining, Shopping' },
  { province_id: 'samutprakan', province_name: 'Samut Prakan', region_id: 'central', visitor_count: 2800000, popularity_factors: 'Ancient City, Erawan Museum' },
  { province_id: 'pathumthani', province_name: 'Pathum Thani', region_id: 'central', visitor_count: 1800000, popularity_factors: 'Dream World, Science Museum, Canals' },
  { province_id: 'lopburi', province_name: 'Lop Buri', region_id: 'central', visitor_count: 1500000, popularity_factors: 'Monkey City, Sunflower Fields, Khmer Ruins' },
  { province_id: 'suphanburi', province_name: 'Suphan Buri', region_id: 'central', visitor_count: 1400000, popularity_factors: 'Dragon Descendants Museum, Sam Chuk Market' },
  { province_id: 'saraburi', province_name: 'Saraburi', region_id: 'central', visitor_count: 1200000, popularity_factors: 'Phra Phutthabat, Waterfalls, Dairy Farms' },
  { province_id: 'samutsongkhram', province_name: 'Samut Songkhram', region_id: 'central', visitor_count: 1100000, popularity_factors: 'Amphawa Floating Market, Fireflies' },
  { province_id: 'samutsakhon', province_name: 'Samut Sakhon', region_id: 'central', visitor_count: 950000, popularity_factors: 'Seafood Hub, Salt Fields' },
  { province_id: 'angthong', province_name: 'Ang Thong', region_id: 'central', visitor_count: 750000, popularity_factors: 'Wat Muang (Big Buddha), Court Dolls' },
  { province_id: 'singburi', province_name: 'Sing Buri', region_id: 'central', visitor_count: 650000, popularity_factors: 'Bang Rachan Memorial, Wat Phikun Thong' },

  // ── ภาคตะวันออก (East - 7 Provinces) ──
  { province_id: 'chonburi', province_name: 'Chon Buri', region_id: 'east', visitor_count: 18500000, popularity_factors: 'Pattaya, Beaches, Koh Larn, Nightlife' },
  { province_id: 'rayong', province_name: 'Rayong', region_id: 'east', visitor_count: 7800000, popularity_factors: 'Koh Samet, Seafood, Fruit Orchards' },
  { province_id: 'trat', province_name: 'Trat', region_id: 'east', visitor_count: 2100000, popularity_factors: 'Koh Chang, Koh Kood, Island Hopping' },
  { province_id: 'chachoengsao', province_name: 'Chachoengsao', region_id: 'east', visitor_count: 1900000, popularity_factors: 'Wat Sothon, Pink Ganesha, River Views' },
  { province_id: 'chantaburi', province_name: 'Chanthaburi', region_id: 'east', visitor_count: 1700000, popularity_factors: 'Gems, Cathedral of Immaculate Conception' },
  { province_id: 'prachinburi', province_name: 'Prachin Buri', region_id: 'east', visitor_count: 850000, popularity_factors: 'Khao Yai Gateway, Herbal Medicine' },
  { province_id: 'nayok', province_name: 'Nakhon Nayok', region_id: 'east', visitor_count: 750000, popularity_factors: 'Khun Dan Dam, Waterfalls, Rafting' },
  { province_id: 'sakaeo', province_name: 'Sa Kaeo', region_id: 'east', visitor_count: 650000, popularity_factors: 'Rong Kluea Market, Pang Sida National Park' },

  // ── ภาคตะวันตก (West - 5 Provinces) ──
  { province_id: 'kanchanaburi', province_name: 'Kanchanaburi', region_id: 'west', visitor_count: 9100000, popularity_factors: 'River Kwai, Erawan Waterfall, Death Railway' },
  { province_id: 'phetchaburi', province_name: 'Phetchaburi', region_id: 'west', visitor_count: 8000000, popularity_factors: 'Cha-am Beach, Palaces, Kaeng Krachan' },
  { province_id: 'prachuapkhirikhan', province_name: 'Prachuap Khiri Khan', region_id: 'west', visitor_count: 7500000, popularity_factors: 'Hua Hin, Sam Roi Yot National Park' },
  { province_id: 'ratchaburi', province_name: 'Ratchaburi', region_id: 'west', visitor_count: 1500000, popularity_factors: 'Damnoen Saduak Floating Market, Art Scene' },
  { province_id: 'tak', province_name: 'Tak', region_id: 'west', visitor_count: 950000, popularity_factors: 'Thi Lo Su Waterfall, Bhumibol Dam' },

  // ── ภาคใต้ (South - 14 Provinces) ──
  { province_id: 'phuket', province_name: 'Phuket', region_id: 'south', visitor_count: 14000000, popularity_factors: 'World-class Beaches, Old Town, Island Tours' },
  { province_id: 'suratthani', province_name: 'Surat Thani', region_id: 'south', visitor_count: 7100000, popularity_factors: 'Koh Samui, Koh Phangan, Khao Sok' },
  { province_id: 'krabi', province_name: 'Krabi', region_id: 'south', visitor_count: 6800000, popularity_factors: 'Phi Phi Islands, Railay, Limestone Cliffs' },
  { province_id: 'songkhla', province_name: 'Songkhla', region_id: 'south', visitor_count: 6500000, popularity_factors: 'Hat Yai, Cross-border Trade, Old Town' },
  { province_id: 'phangnga', province_name: 'Phang Nga', region_id: 'south', visitor_count: 4500000, popularity_factors: 'Similan Islands, James Bond Island' },
  { province_id: 'nakhonsithammarat', province_name: 'Nakhon Si Thammarat', region_id: 'south', visitor_count: 1800000, popularity_factors: 'Wat Phra Mahathat, Kiriwong Village' },
  { province_id: 'trang', province_name: 'Trang', region_id: 'south', visitor_count: 1300000, popularity_factors: 'Underwater Wedding, Food Scene, Emerald Cave' },
  { province_id: 'chumphon', province_name: 'Chumphon', region_id: 'south', visitor_count: 950000, popularity_factors: 'Gateway to the South, Diving' },
  { province_id: 'ranong', province_name: 'Ranong', region_id: 'south', visitor_count: 750000, popularity_factors: 'Hot Springs, Little Koh Chang' },
  { province_id: 'phatthalung', province_name: 'Phatthalung', region_id: 'south', visitor_count: 650000, popularity_factors: 'Thale Noi, Buffaloes in the Water' },
  { province_id: 'satun', province_name: 'Satun', region_id: 'south', visitor_count: 600000, popularity_factors: 'Koh Lipe, Tarutao National Park' },
  { province_id: 'pattani', province_name: 'Pattani', region_id: 'south', visitor_count: 450000, popularity_factors: 'Krue Se Mosque, Lim Ko Niao Shrine' },
  { province_id: 'yala', province_name: 'Yala', region_id: 'south', visitor_count: 420000, popularity_factors: 'Betong, Sea of Mist, Betong Chicken' },
  { province_id: 'narathiwat', province_name: 'Narathiwat', region_id: 'south', visitor_count: 400000, popularity_factors: 'Budo-Sungai Padi, Phra Phuttha Thaksin Ming Mongkhon' },
];
